### ISSUE TITLE
Forecast is missing.

### ISSUE THREAD

**Issue by bakboord4** [mlamberts78/weather-chart-card#102]
**Describe the bug**
TypeError: undefined is not an object (evaluating 'forecast[3].datetime') drawChart.

For Safari on macOS, IO and /iPadOS.
Error introduced with version 2.3.0

**To Reproduce**
Just show the chart on screen.

**Expected behavior**
Return of forecast.

**Screenshots**

<img width="541" alt="Scherm­afbeelding 2024-02-18 om 12 09 53" src="https://github.com/mlamberts78/weather-chart-card/assets/42673768/dd762223-354f-410f-858c-62bc52576fa4">

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION: V2.3.0
 - HA 2024.2.2
 - OS: 11.5
 - Browser Safari
 - Version 17.3.1

**Additional context**

Logger: frontend.js.latest.202402071
Source: components/system_log/__init__.py:306
First occurred: 17 februari 2024 om 16:00:09 (11 occurrences)
Last logged: 11:57:38

Uncaught error from Safari 17.3.1 on Mac OS 10.15.7 TypeError: undefined is not an object (evaluating 'forecast[3].datetime') drawChart (/hacsfiles/weather-chart-card/weather-chart-card.js:17964:27) callback (/hacsfiles/weather-chart-card/weather-chart-card.js:17750:19) message (node_modules/home-assistant-js-websocket/dist/connection.js:23:42) forEach ([native code]::) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

Uncaught error from WebKit 605.1.15 on Mac OS 10.15.7 TypeError: undefined is not an object (evaluating 'forecast[3].datetime') drawChart (/hacsfiles/weather-chart-card/weather-chart-card.js:17964:27) callback (/hacsfiles/weather-chart-card/weather-chart-card.js:17750:19) message (node_modules/home-assistant-js-websocket/dist/connection.js:23:42) forEach ([native code]::) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

Uncaught error from WebKit 605.1.15 on iOS 17.3.1 TypeError: undefined is not an object (evaluating 'forecast[3].datetime') drawChart (/hacsfiles/weather-chart-card/weather-chart-card.js:17964:27) callback (/hacsfiles/weather-chart-card/weather-chart-card.js:17750:19) message (node_modules/home-assistant-js-websocket/dist/connection.js:23:42) forEach ([native code]::) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

Uncaught error from Safari 17.3 on Mac OS 10.15.7 TypeError: undefined is not an object (evaluating 'forecast[3].datetime') drawChart (/hacsfiles/weather-chart-card/weather-chart-card.js:17964:27) callback (/hacsfiles/weather-chart-card/weather-chart-card.js:17750:19) message (node_modules/home-assistant-js-websocket/dist/connection.js:23:42) forEach ([native code]::) forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)

**Comment by mlamberts78** [comment]
Hello, can you provide output of the weather data?
Developer tools - services - Get weather forecast.

and which weather integration are you using?

**Comment by bakboord4** [comment]
@mlamberts78 
Weather integration is: KNMI 
Requested output.

weather.knmi_casa:
  forecast:
    - datetime: "2024-02-17T23:00:00+00:00"
      condition: cloudy
      templow: 8
      temperature: 10
      precipitation_probability: 0
      wind_bearing: 225
      wind_speed: 19
      wind_speed_bft: 3
      sun_chance: 24
    - datetime: "2024-02-18T23:00:00+00:00"
      condition: pouring
      templow: 7
      temperature: 10
      precipitation_probability: 80
      wind_bearing: 270
      wind_speed: 15
      wind_speed_bft: 3
      sun_chance: 20
    - datetime: "2024-02-19T23:00:00+00:00"
      condition: rainy
      templow: 4
      temperature: 11
      precipitation_probability: 40
      wind_bearing: 225
      wind_speed: 15
      wind_speed_bft: 3
      sun_chance: 20

**Comment by mlamberts78** [comment]
Thanks, I know the root cause (knmi data has only 3 days forecast) and wil implement a fix in the next release.  V2.2.9 should work for you for the time being… ( via HACS choose redownload and select older version)

**Comment by bakboord4** [comment]
@mlamberts78 
Thanks for the temp. fix. Forecast is back again.
Looking forward to the new release.

**Comment by bakboord4** [comment]
@mlamberts78 
You may have already seen it. 
See https://github.com/golles/ha-knmi/pull/120, chapter weather where is mentioned: 5 day forecast and hourly forecast. May be of influence on your fix.
