### ISSUE TITLE
Add number of forecasts

### ISSUE THREAD

**Issue by dbustosrc** [mlamberts78/weather-chart-card#105]
**Is your feature request related to a problem? Please describe.**
The number of forecasts displayed depends on the size of the screen, therefore the information changes depending on where it is viewed from, which makes it difficult to adjust it to the size and distribution of other components.
![2024-02-19_131101](https://github.com/mlamberts78/weather-chart-card/assets/26286623/f0eb8a9c-3b3f-4611-a7c9-0c069e5eae14)

**Describe the solution you'd like**
A parameter could be added in the header that allows limiting the maximum number of forecasts to be displayed
`number_of_forecasts: 5 `

**Additional context**
You can see within other projects that also use a similar parameter like [bramkragten/weather-card](https://github.com/bramkragten/weather-card) or [decompil3d/lovelace-hourly-weather](https://github.com/decompil3d/lovelace-hourly-weather)

**Comment by antcodd** [comment]
Thanks for implementing this!

The wind forecast labels don't seem to be adjusting to an increased number of forecasts and become misaligned and fall outside the card (I've tried reducing the font size but it is the padding that is the problem).

**Comment by jeffjensen** [comment]
Yes, this is a very nice feature!

I noted similar issue when specifying larger counts.  I wondered if could also stack the direction and the speed vertically to help.

**Comment by antcodd** [comment]
Please don't limit to the auto numbe (though it looks like you edited your message). It's very useful to display 8 or even 24 houre at a time and the chart works very well. If you don't want to fix overlapping icons/wind text maybe just disable those features if the number is too big (or just leave it as the user's problem for now).

The forecast icons work OK up to about 12 hours on a mobile screen, for 24 hours I have disabled the icons as there's no way that's going to fit sensibly but the chart works nicely (it even displays every second temperature number and time to fit properly). I'll live without the wind speed for now, I might try making the scaling more dynamic at some point.
