### ISSUE TITLE
Precipitation probability type incorrectly represented on the canvas graph

### ISSUE THREAD

**Issue by dbustosrc** [mlamberts78/weather-chart-card#122]
**Is your feature request related to a problem? Please describe.**
The probability of rain represented on the graph is presented incorrectly, for example. At 55% probability it shows a full bar as if it were 100% instead of a half bar closer to 50% because it is the maximum probability taken and from there it calculates the rest down 48%, 40%, and 17%
![imagen](https://github.com/mlamberts78/weather-chart-card/assets/26286623/05a19b2d-9b77-4b94-b110-1720720985e0)

**Describe the solution you'd like**
The sample should always be graphed from 100% down, and not take the maximum probability as 100% in the sample

**Additional context**
Edited screenshot of what the graph should look like:
Card code:
```type: custom:weather-chart-card
entity: weather.tomorrow_io_home_hourly
show_main: false
show_attributes: false
sun: sun.sun
mode: hourly
locale: es
forecast:
  condition_icons: true
  show_wind_forecast: false
  precipitation_type: probability
  labels_font_size: 17
  type: hourly
  style: style2
  number_of_forecasts: '5'
units:
  pressure: ''
  speed: ''
use_12hour_format: false
animated_icons: true
icon_style: style2
```

![imagen](https://github.com/mlamberts78/weather-chart-card/assets/26286623/a05338bf-2518-49ba-b1c7-6f70005e076f)

**Comment by mlamberts78** [comment]
`precipitation_type` setting is removed and replaced by `show_probability` setting. `show_probability` will show the probability next to the rainfall. The bars will show the rainfall with < 20mm as full
