### ISSUE TITLE
UTC-time on my LG TV

### ISSUE THREAD

**Issue by RH-Dreambox** [mlamberts78/weather-chart-card#128]
**Describe the bug**
For some unknown reason, the Weather Chart Card shows the wrong time when I open HA on my LG TV (OLED55C8PLA).
It shows UTC time which is -1 hour here in Sweden. All other devices such as computer, tablet and mobile phone show the time correctly.
The TV is configured to the correct time zone and the system time is correct. I still guess that the TV is the problem, but I don't know if it can be fixed.

**To Reproduce**
1. Open HA on my TV
2. Show Weather Chart Card
3. Compare time

**Expected behavior**
The time should be +1 hour

**Screenshots**

**Desktop (please complete the following information):**
Weather Chart Card
Version 2.4.0

HomeAssistant
Core 2024.2.5
Supervisor 2024.02.1
Operating System 12.0
Frontend 20240207.1

 - Browser LG TV

**Additional context**
No high prio

**Comment by mlamberts78** [comment]
Is the time only wrong on the weather chart card or do you have the issue with other HA cards as well?
If you are using the browser on the LG TV, can you check this website and see what time is displayed? https://webbrowsertools.com/timezone/

**Comment by RH-Dreambox** [comment]
Hi, and thank you for quick answer.

 

I attach a screen shot from my TV and a text file from my computer and they both show the correct time.

I show the time in several places in my dashboards and then the time is correct.

 

But on the TV I now discovered the same error in a graph (Apexcharts-card) where I show Tibber electricity price per hour.

The bottom of the graph shows the correct time, but when I place the mouse over the current curve, the pop-up dialogue shows the wrong time. 

 

When I show the same graph on the computer, the time is displayed correctly.

 

Best Regards

Roy

 

Text from my computer

Timezone info

 

Time on Server                                                        Mon, 04 Mar 2024 08:16:01 GMT

Time on Local Machine                                         Mon Mar 04 2024 09:30:45 GMT+0100 (centraleuropeisk normaltid)

Time from Intl.DateTimeFormat #1                 Monday, March 4, 2024 at 9:30:45 AM GMT+1

Time from Intl.DateTimeFormat #2                 måndag 4 mars 2024 kl. 9:30:45 fm centraleuropeisk normaltid

Internet Beat  around @396

Timezone         Europe/Stockholm

Timezone         Offset                -60 minutes

Numbering      System              latn

Locale                sv

Calendar           gregory

Day                     2-digit

Month               2-digit

Year                    numeric

Milliseconds since January 1, 1970                   1709541045725

09:33:42

Mon, Mar - 04 - 2024

 

Från: mlamberts78 ***@***.*** 
Skickat: den 3 mars 2024 19:44
Till: mlamberts78/weather-chart-card
Kopia: RH-Dreambox; Author
Ämne: Re: [mlamberts78/weather-chart-card] UTC-time on my LG TV (Issue #128)

 

Is the time only wrong on the weather chart card or do you have the issue with other HA cards as well?
If you are using the browser on the LG TV, can you check this website and see what time is displayed? https://webbrowsertools.com/timezone/

**Comment by MankiniChykan** [comment]
> Hi, I don't want to hijack this issue but since you are probably working on the time section of this integration I would like to ask for a modification to use the time of the home assistant server instead of the browser time. I have several HA locations and when I call one from a different time zone I always get the hourly forecast starting with my browser time. Thank you

Home Assistant Server Time is what is needed, rather than Browser Time. Especially for those that travel multiple Time Zones. Related to this bug.
https://github.com/mlamberts78/weather-chart-card/issues/134#issue-2174763627

**Comment by pedromfa** [comment]
+1 for Server Time instead of Browser Time. Thank you for the great project here! ;)

**Comment by pedromfa** [comment]
Any luck on this? :(

**Comment by jezinke** [comment]
It looks like the card pulls the correct hourly data (based on server time) from the weather entity but displays wrong hours (based on browser time). Hope this helps to find athe problem and solve it. thank you.
