### ISSUE TITLE
BEFORE REPORTING AN ISSUE

### ISSUE THREAD

**Issue by mlamberts78** [mlamberts78/weather-chart-card#13]
Use Bug report or Feature request template for valid issues.
Issues not using the Bug Report or Feature request template will be ignored/closed.
If you have a question or concern, open a [Discussion](https://github.com/mlamberts78/weather-chart-card/discussions), not an issue.

Please make sure you are running the latest release of the weather-chart-card.

**Comment by vladimir-danek** [comment]
![Screenshot_2024-02-28-17-56-28-470_io homeassistant companion android-01](https://github.com/mlamberts78/weather-chart-card/assets/128029994/578db4fe-68c6-4e50-beb3-571d68796288)
Hi, 
the graph is missing in the widget. Does anyone know where the error is, please?

Home Assistant 2023.5.4 snapscraft

Thank You very much.
Lada Danek
