### ISSUE TITLE
Midnight shows as 24:00 Rather than 0:00

### ISSUE THREAD

**Issue by MankiniChykan** [mlamberts78/weather-chart-card#134]
**Describe the bug**
Midnight shows as 24:00 on main clock

**Expected behavior**
Midnight to show as 0:00

**Screenshots**

![Screenshot_20240304-000413](https://github.com/mlamberts78/weather-chart-card/assets/101962955/7d9137a1-3682-430d-b0cf-3989d6cb0144)

**Comment by mlamberts78** [comment]
Please check if other cards with a clock have the same behavior, looks like a HA locale issue.

**Comment by MankiniChykan** [comment]
> Please check if other cards with a clock have the same behavior, looks like a HA locale issue.

Will do, will have to wait till midnight.

**Comment by MankiniChykan** [comment]
My Home Assistant Server lives Tasmania GMT+11 and I am currently working in Western Australia GMT+8 with a three hour time difference.
Is the card reading the time from the device that is being used? I have noticed that if I use the companion app or log into a computer browser that the card seems to be showing the local time of the devices I am using in WA. 

This card https://github.com/pkissling/clock-weather-card is showing the correct Tasmanian time. I think wherever the clock data is being pulled from needs to be changed.

**Comment by soulripper13** [comment]
Same problem here. I'm in a different time zone and it shows be my present location time. Any fix?

**Comment by MankiniChykan** [comment]
They will have to allow a setting to allow server time, it is currently 
reading browser time.

---
Andrew (Chicken) Hunter
0417525998

On 2024-05-29 00:22, soulripper13 wrote:

> Same problem here. I'm in a different time zone and it shows be my 
> present location time. Any fix?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/mlamberts78/weather-chart-card/issues/134#issuecomment-2135659669
[2]
