### ISSUE TITLE
Option for no forecast graph in card

### ISSUE THREAD

**Issue by wigster** [mlamberts78/weather-chart-card#135]
**Is your feature request related to a problem? Please describe.**

I would like to be able to not display the temperature/rain forecast graph, but limit the card to just the weather condition icons. I am plotting the temps elsewhere by myself together with historical data, but it would be great to be able to add a narrow stripe with the condition icons. 

**Describe the solution you'd like**
A subkey to switch off the graph in the forecast key, e.g. show_temperature_forcast: false

**Comment by mlamberts78** [comment]
Can you try it by setting this option?
forecast: 
    chart_height: ‘0.1'
