### ISSUE TITLE
style2 chart not showing (except randomly they are)

### ISSUE THREAD

**Issue by kingpode** [mlamberts78/weather-chart-card#141]
**Describe the bug**
I am trying to use temperature charts of style2.  Most of the time they come out as style1.  Randomly they do appear in style2, but that is quite rare, for some reason.  They never seem to be style2 on an android tablet, sometimes are on Chrome browser running on Linux Mint.

**To Reproduce**
1. Go to 'lovelace interface, edit view.
3. Click on 'add card, default settings, except change chart style1 -> style2
4. First charts are style2, but
5. Reloading page (Shift-F5 in browser) switches charts to back to style1.

**Expected behavior**
Excepting to keep seeing style2 charts

**Screenshots**
![shot1](https://github.com/mlamberts78/weather-chart-card/assets/114421893/ae287cd9-84e3-4a9e-96a6-5699dcc9c8c6)
![shot2](https://github.com/mlamberts78/weather-chart-card/assets/114421893/6a8868ac-8858-4ec3-a713-130a1ba4b3b3)

**Desktop (please complete the following information):**
 - V2.4.2
 - 2024.3.0
 - 12.0
 - chrome on linux, and Homeassistant client on Android
 - Version 124.0.6342.3 (Official Build) dev (64-bit)

**Additional context**
Also: after browser refresh, icon style goes to defaul (i guess), and visual editor seems to stop working. This might be related to the issue?

**Comment by mlamberts78** [comment]
The "no visual editor available" is also not correct, can you try to remove the card via HCS and re-download it?
Do you also have weather-card installed? There is a conflict at the moment which will be resolved in the next release: #138

**Comment by kingpode** [comment]
Really sorry about this issue, I am embarrased.  I had a (very) old manual installation sitting around of this same widget, newer version was via HACS. Deleted the old one, and it is now working,  I couldn't delete the post, hence I closed the issue.

Sorry again, and thank you :)
