### ISSUE TITLE
WEATHERFLOW FORECAST FOR CHART CARD

### ISSUE THREAD

**Issue by Aham330** [mlamberts78/weather-chart-card#143]
I use to be able to use a weather entity with a forecast but this feature has now been changed. The Entity is no longer a weather entity but it is now forecast. Somehow forecast entity is not available for the weather-chart-card.

Could it be possible to let this integration and the this one; https://github.com/briis/weatherflow_forecast talk to each other?

If this is already possible please tell me how ;-)

**Comment by mlamberts78** [comment]
The card expect a weather. entity.
More info: https://developers.home-assistant.io/docs/core/entity/weather/
