### ISSUE TITLE
Support National Weather Service (United States) daily forecast (chart is missing)

### ISSUE THREAD

**Issue by drewkeller** [mlamberts78/weather-chart-card#145]
**Is your feature request related to a problem? Please describe.**
weather-chart-card is awesome, but apparently it does not fully support National Weather Service (United States) daily forecast (chart is missing).

**Describe the solution you'd like**
I would like weather-chart-card to show the daily forecast (chart) with National Weather Service data (United States) as the provider. I set up an apex chart card for the forecast min/max and that is working.

**Additional context**
https://weather-gov.github.io/api/general-faqs

![accuweather-news-compare](https://github.com/mlamberts78/weather-chart-card/assets/954172/5d475487-f465-4078-878b-9ecd0bd81442)

![nws-settings](https://github.com/mlamberts78/weather-chart-card/assets/954172/5212e7ae-d1cb-4389-b2a4-0c8b6714629f)

![nws-settings-apex-chart](https://github.com/mlamberts78/weather-chart-card/assets/954172/ddf918c1-6a89-44c9-a7f3-1e0d88465812)

**Comment by mlamberts78** [comment]
Unfortunately the National Weather Service integration doesn't support daily forecast, it is doing twice_daily forecast which is not the same.

**Comment by MaxMyzer** [comment]
> Unfortunately the National Weather Service integration doesn't support daily forecast, it is doing twice_daily forecast which is not the same.

is there a reason to not support `twice_daily`?
