### ISSUE TITLE
Even more alternate entities :-)

### ISSUE THREAD

**Issue by silke-99** [mlamberts78/weather-chart-card#149]
I just detected this great card and like it very much. As I operate my own weather station, the "alternate entities" are especially useful!

Apart from the ones already requested (dewpoint, current rain rate), "total rainfall today" would be a nice additional info.

Thanks for your work! :-)

**Comment by mlamberts78** [comment]
All supported attributes in this card are official properties for weather: https://developers.home-assistant.io/docs/core/entity/weather/

total rainfall today isn't.

**Comment by majorsl** [comment]
If I may tag on to this request rather than starting a very similar one.  An alternate entity to use the various weather warnings/alert Intergrations in HA would be fantastic to display in this card.
