### ISSUE TITLE
M/s when using weather integration with m/s as default

### ISSUE THREAD

**Issue by cappadanna** [mlamberts78/weather-chart-card#15]
**Describe the bug**
When using the smhi weather integration it uses m/s as default wind unit. When selecting m/s in the card it converts from km/h to m/s. For instance smhi reports 3,9m/s the card converts it to 1. 

[Smhi](https://www.home-assistant.io/integrations/smhi/)

**Comment by mlamberts78** [comment]
Thanks for reporting, I will fix this bug when implementing the support for imperial weather units. this will be included in V1.7.
