### ISSUE TITLE
Daily weather forcast bug

### ISSUE THREAD

**Issue by emrares** [mlamberts78/weather-chart-card#154]
I selected the daily wetaher forcast but instead of the weak days it just shows 12:00

![Screenshot 2024-03-29 225205](https://github.com/mlamberts78/weather-chart-card/assets/67040145/22e2cd62-aca7-4222-8b50-6d1bc9fcc776)

![Screenshot 2024-03-29 225414](https://github.com/mlamberts78/weather-chart-card/assets/67040145/e90d152b-bd1e-41f1-8300-03352e006af9)

**Comment by mlamberts78** [comment]
Please provide more information:
Used card version
Used weather integration
Output of the forecast data

**Comment by emrares** [comment]
Nevermind, redownload version 2.4.5 and now it's fine.
