### ISSUE TITLE
Add wind gust speed option to detailed forecast 

### ISSUE THREAD

**Issue by gcoan** [mlamberts78/weather-chart-card#155]
I see the latest release includes wind gust information but it only appears to be an option for the main card. 

I'd like to be able to see this on the detailed forecast to show alongside wind speed over time

**Comment by gcoan** [comment]
any update to this?

**Comment by folfy** [comment]
Might gonna look into this, would be rly good to have this feature - Could you reopen the issue?

**Comment by gcoan** [comment]
> Might gonna look into this, would be rly good to have this feature - Could you reopen the issue?

Doesn’t look like I have the permissions to be able to reopen this
