### ISSUE TITLE
Include entity for UV custom sensor

### ISSUE THREAD

**Issue by joe-sydney** [mlamberts78/weather-chart-card#16]
**Is your feature request related to a problem? Please describe.**

I am using the OpenUV integration and it would be good if the current UV level could be displayed within this card in the attributes section.

**Describe the solution you'd like**

Allow a custom sensor to be configured for current UV level by specifying an entity_id for the UV level (in a similar way for temp, humidity, pressure). 

This could then be shown in the attributes section.

**Additional context**

**Comment by mlamberts78** [comment]
Please let me know if this screenshot is matching your desired solution:
![uv](https://github.com/mlamberts78/weather-chart-card/assets/93537082/8f4af6c8-83db-4175-aba6-5cc4f3e64f02)

**Comment by joe-sydney** [comment]
That looks great, thanks!

**Comment by mlamberts78** [comment]
This is also an option, let me know which one you like:
![uv](https://github.com/mlamberts78/weather-chart-card/assets/93537082/cc3c029e-68d2-4694-9740-ecc74a06977d)

**Comment by joe-sydney** [comment]
Thanks, but I wasn't able to tell the difference between the 2. I also wonder if introducing a 4th column may make the display challenging especially on a phone. Perhaps the original UV value could be put under or above the sunrise and sunset values?

**Comment by mlamberts78** [comment]
Thanks, will always test it on multiple devices, if it doesn't fit I will place it below the sunset values. The difference: 
2.4 UV
or
UV: 2.4

**Comment by jrspowers** [comment]
"How do I add the UV sensor to the config?"

**Comment by mlamberts78** [comment]
> "How do I add the UV sensor to the config?"

You can add the following configuration option in your yml card configuration:
uv: sensor.current_uv_index

It is also possible to configure the UV entity in the visual card configurator under “alternate entities”.

Make sure you have installed an UV index integration, like “OpenUV”

**Comment by jrspowers** [comment]
> > "How do I add the UV sensor to the config?"
> 
> 
> 
> You can add the following configuration option in your yml card configuration:
> 
> uv: sensor.current_uv_index
> 
> 
> 
> It is also possible to configure the UV entity in the visual card configurator under “alternate entities”.
> 
> 
> 
> Make sure you have installed an UV index integration, like “OpenUV”

Thanks tis work nice 😊
