### ISSUE TITLE
broken in version 2024.4.2

### ISSUE THREAD

**Issue by unosakk** [mlamberts78/weather-chart-card#162]
**Describe the bug**
after upgrade forecast is not working with accweather or openweather

**To Reproduce**
add card
nothing is shown / peale, chekck your weather entity

**Screenshots**
![image](https://github.com/mlamberts78/weather-chart-card/assets/67309358/e586d920-3c17-4f05-bd24-869b38d3721c)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION V2.4.5
 - 2024.4.2

**Comment by mlamberts78** [comment]
Can you check this issue and see if it also solves you problem? https://github.com/mlamberts78/weather-chart-card/issues/157#issuecomment-2039732945

**Comment by unosakk** [comment]
> Can you check this issue and see if it also solves you problem? [#157 (comment)](https://github.com/mlamberts78/weather-chart-card/issues/157#issuecomment-2039732945)

this fixed it. tnx
