### ISSUE TITLE
Chart not updating without page reload

### ISSUE THREAD

**Issue by nzottmann** [mlamberts78/weather-chart-card#170]
**Describe the bug**
I have the card running on a dashboard, thus the page in the browser is not reloaded very often. The chart does not update without reloading the browser.
- The first day of the forecast stays the same and does not change on midnight
- The temperature and other values do not change.

I included the current time and the temperature of a sensor as override, those two get updated.

**To Reproduce**
Open the dashboard containing the card and wait. After a day, open the dashboard in another tab or on another device and compare the forecast.

**Expected behavior**
The forecast should be updated regularly. The first day should always be the current day, thus change on midnight.

**Desktop (please complete the following information):**
 - v2.4.5
 - HA 2024.4.3
 - HA OS 11.5
 - Chromium 122.0.6261.89

**Additional context**
I found someone reporting the same problem: https://community.home-assistant.io/t/lovelace-weather-chart-card/638917/22?u=nils_z

**Comment by waroen** [comment]
Same here, very obvious with hourly forecasts that it doesn't update until reloaded. It might update if the underlying weather entity updates, because I find that it updates sometimes.

**Comment by asantaga** [comment]
Also have this issue.. Is there a way we can manually reload the chart, maybe using automation or browser_mod?

**Comment by WhiteSockedDancer** [comment]
I've got the same problem. Using a Dashboard on a Smart Mirror and it doesnt update the chart over time. :/

**Comment by allan-gersfelt-larsen** [comment]
I see the same problem.
