### ISSUE TITLE
Wind direction is not shown in the attributes section when the weather entity uses text-based cardinal direction

### ISSUE THREAD

**Issue by joe-sydney** [mlamberts78/weather-chart-card#18]
**Describe the bug**

Wind direction is not shown in the attributes section. I can see in the weather entity that the wind bearing is provided in text form cardinal direction e.g. WSW (rather than in azimuth angle degrees). 

As a work around for now, I made a change to the weather integration I am using to convert from cardinal direction to azimuth angle and the card now displays correctly.

According to the HA weather entity documentation:
The current wind bearing in azimuth angle (degrees) or 1-3 letter cardinal direction.

By the way, thanks for adding UV level to the attributes per previous feature request.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE (e.g.  2023.07.3)
 - OS: [e.g. 10.3, venv, etc.]

**Additional context**

**Comment by mlamberts78** [comment]
Can you tell me which weather integration you are using and provide me a sample output of the attributes?

**Comment by joe-sydney** [comment]
Hi again

I am using the Bureau of Meteorology integration: https://github.com/bremor/bureau_of_meteorology

The attributes are as follows. As you can see the wind bearing is in the form of NNW, which didn't display at all in the card. I made some changes to the weather integration by converting NNW to the corresponding angle, and that worked in the card.

temperature: 13.7
temperature_unit: °C
humidity: 68
pressure_unit: hPa
wind_bearing: NNW
wind_speed: 11
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- datetime: '2023-07-31T00:00:00+10:00'
  condition: clear-night
  templow: null
  precipitation_probability: 0
  temperature: 23
  precipitation: 0
- datetime: '2023-08-01T00:00:00+10:00'
  condition: sunny
  templow: 7
  precipitation_probability: 5
  temperature: 23
  precipitation: 0
- datetime: '2023-08-02T00:00:00+10:00'
  condition: sunny
  templow: 10
  precipitation_probability: 30
  temperature: 21
  precipitation: 1
- datetime: '2023-08-03T00:00:00+10:00'
  condition: sunny
  templow: 8
  precipitation_probability: 0
  temperature: 23
  precipitation: 0
- datetime: '2023-08-04T00:00:00+10:00'
  condition: sunny
  templow: 8
  precipitation_probability: 20
  temperature: 25
  precipitation: 0
- datetime: '2023-08-05T00:00:00+10:00'
  condition: rainy
  templow: 11
  precipitation_probability: 60
  temperature: 21
  precipitation: 5
- datetime: '2023-08-06T00:00:00+10:00'
  condition: rainy
  templow: 8
  precipitation_probability: 60
  temperature: 19
  precipitation: 2
- datetime: '2023-08-07T00:00:00+10:00'
  condition: rainy
  templow: 8
  precipitation_probability: 60
  temperature: 20
  precipitation: 2

attribution: Data provided by the Australian Bureau of Meteorology
icon: mdi:weather-night
friendly_name: Sydney

**Comment by joe-sydney** [comment]
Also, I notice that 180 deg is shown as S(outh) on the card as expected, but the arrow points upwards. And 0 shows as N with the arrow pointing downwards. Is this the intended behavior?

Thanks!

**Comment by mlamberts78** [comment]
Thanks for the information.
This is the currrent configuration for the wind direction:

0 to 22.5 degrees: N (North)
22.5 to 67.5 degrees: NE (Northeast)
67.5 to 112.5 degrees: E (East)
112.5 to 157.5 degrees: SE (Southeast)
157.5 to 202.5 degrees: S (South)
202.5 to 247.5 degrees: SW (Southwest)
247.5 to 292.5 degrees: W (West)
292.5 to 337.5 degrees: NW (Northwest)
337.5 to 360 degrees (or 0 degrees): N (North)

Seems correct to me.

Will have a look to the condition wind speed and wind bearing 0.

**Comment by joe-sydney** [comment]
By the way, please ignore what I said about the icons and direction of the arrows. It was my misunderstanding what wind direction means. I know understand that North means wind is coming from the North, hence the arrow points downwards.

I had a look at the js file itself, and can see that it expects wind direction from the weather entity to be provided as a number (angle in degrees). The weather integration as indicated above does not provide the angle, but provides the direction in text, eg NW and so on. As mentioned, I modded the integration to convert from the cardinal direction test (NW) to an angle and that works with your card. I will have a look at the card to see if I can check whether the direction is provided as an angle or a text-form cardinal direction, and act accordingly.

Thanks again

**Comment by mlamberts78** [comment]
Thanks, I understand the issue and will support the input of the wind direction format like WSW in the next release.

**Comment by joe-sydney** [comment]
> Thanks, I understand the issue and will support the input of the wind direction format like WSW in the next release.

I reverted the weather integration to provide the text-form cardinal direction, and made some tweaks to the card to work with that... in case the following might be useful, I just checked deg to see if it number type in getWindDirIcon and getWindDir. Also added an additional icon consisting of a minus (-) sign, to use when there is no wind or other error condition (ie index 9 below).


    getWindDirIcon(deg) {
      if ( typeof deg == 'number' ) {
        return cardinalDirectionsIcon[parseInt((deg + 22.5) / 45.0)];
      } else {
        var i = 9;
        switch (deg) {
          case "N":
            i = 0;
            break;
          case "NNE":
          case "NE":
            i = 1;
            break;
          case "ENE":
          case "E":
            i = 2;
            break;
          case "ESE":
          case "SE":
            i = 3;
            break;
          case "SSE":
          case "S":
            i = 4;
            break;
          case "SSW":
          case "SW":
            i = 5;
            break;
          case "WSW":
          case "W":
            i = 6;
            break;
          case "WNW":
          case "NW":
            i = 7;
            break;
          case "NNW":
            i = 8;
            break;
          default:
            i = 9;
            break;
        }
        return cardinalDirectionsIcon[i];
      }
    }

    getWindDir(deg) {
      if ( typeof deg == 'number' ) {
        return this.ll('cardinalDirections')[parseInt((deg + 11.25) / 22.5)];
      } else {
        return deg;
      }
    }

**Comment by joe-sydney** [comment]
I found that the sun.sun == below_horizon check didn't work and the day time icon was displayed during the night. In the card, I see that this check only applied for custom icons. I made a tweak so it worked also for the standard hass icons.

BTW, I also changed the above code to using an associative array, so the text N, NE, etc, returns an index to the original cardinalDirectionsIcon array, and that's working too.

**Comment by mlamberts78** [comment]
Thanks, I will release a new version with this fixes end of this week. Will include the fix for for the check below horizon for the main icons as well.

**Comment by mlamberts78** [comment]
I checked your statement about the default icons during night, default HA icons only support clear night, unfortunatly night partly cloudy is not supported: https://www.home-assistant.io/integrations/weather/

**Comment by joe-sydney** [comment]
> I checked your statement about the default icons during night, default HA icons only support clear night, unfortunatly night partly cloudy is not supported: https://www.home-assistant.io/integrations/weather/

It is strange that HA documentation didn't include hass:weather-night-partly-cloudy as that is a valid MDI icon...

![image](https://github.com/mlamberts78/weather-chart-card/assets/74637159/4d1abeb6-8e20-41c6-8737-b85afc76dae7)
