### ISSUE TITLE
Wind Direction is inverted. 

### ISSUE THREAD

**Issue by soulripper13** [mlamberts78/weather-chart-card#182]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION 2.4.6
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE (Home Assitant OS 2024.5.5)

**Additional context**
Wind Blowing east but arrow showing west. For all direction the arrow is inverted

**Comment by mlamberts78** [comment]
See https://windy.app/blog/what-is-wind-direction.html
wind direction is correct.

Also reported earlier in #95
