### ISSUE TITLE
When there is to many Numbers of forecast some info is displayed outside of the card

### ISSUE THREAD

**Issue by vojacekj** [mlamberts78/weather-chart-card#185]
**Describe the bug**
When I set up hourly forecast and set numbers of forecast to some "higher" numbers like 10 or 18 (to see more hours in graph) some data are spilled outside of the card (see screenshot)

**To Reproduce**
1. Go to 'Dashboard'
2. Add weather-chart-card
3. Configure it to Forecast type: Hourly forecast
4. Go to Settings -> Forecast
5. Set 'Number of forecasts' to for example 18
6. Save card
7. See that data is overflowed 

**Expected behavior**
Data are inside the card only

**Screenshots**
<img width="774" alt="image" src="https://github.com/mlamberts78/weather-chart-card/assets/59819185/351939ed-c2d0-4b18-b916-a3d9e60df533">

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION: V2.4.6
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE: 
 Core: 2024.6.1
Frontend: 20240605.0
Installation type: Docker on Raspberry Pi 4 
 - OS: macOS 14.5 , android 10
 - Browser: chrome on mac (version 125.0.6422.142) , companion app (android - 2024.6.1-full)

**Comment by vojacekj** [comment]
Hello why this was closed without any activity ? This is still persistent bug, this is not the way to handle issues

**Comment by dxmnkd316** [comment]
> Hello @mlamberts78 why this was closed without any activity ? This is still persistent bug, this is not the way to handle issues

It's automatic.  If you don't reply after the stale issue warning, it will automatically close it to clean-up old issues.

This is a very common way to handle issues.

That said, I have this issue as well.  I've tried to fix it in my fork but haven't fully solved it.  I can get it to skip every X hours but it doesn't line up quite right with how I set the major ticks on the chart.
