### ISSUE TITLE
Wind guust speed using too many decimal places

### ISSUE THREAD

**Issue by cryptk** [mlamberts78/weather-chart-card#196]
**Describe the bug**
Despite my wind gust sensor being set to 2 decimal places, the card is rendering a lot more decimal places

**To Reproduce**
1. Have a wind gust speed sensor
2. Set it to a reasonable number of decimal places (this is what mine is set to by default)
3. Observe the wind gust speed using a lot of decimal places in the card

**Expected behavior**
I expect the card to respect the requested number of decimal places on the sensor just as everything else does

**Screenshots**
![Untitled](https://github.com/mlamberts78/weather-chart-card/assets/421501/767e3315-84e2-499a-8fc3-92b62a0af7fd)

**Desktop (please complete the following information):**
 - v2.4.7
 - 2024.6.3
 - OS: 12.3
 - Browser firefox
 - Version 127.0

**Additional context**
It doesn't seem to matter what number of decimal places I request for any of the sensors, the card seems to ignore those settings.  That said, while it implements it's own rounding for most things, it does not appear to round the gust speed at all.

Ideally, the card should respect the user selected rounding, but it should at least round the gust speed to some sane number of decimal places.

**Comment by bb12489** [comment]
This is happening for me as well. I even tried changing the display precision on my humidity sensor, but the card does not reflect this change. 
![image](https://github.com/user-attachments/assets/53daf196-786b-4af9-af04-c779e0c015bc)

**Comment by bb12489** [comment]
I'm having the same issue here with displaying my barometric pressure from my weather station. I've changed the display precision on the sensors itself to round the number, but this isn't being displayed on the weather card. 
![image](https://github.com/user-attachments/assets/24c31470-6080-4e63-b74a-8d7ee3760ea3)
