### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by pennisiandrea** [mlamberts78/weather-chart-card#198]
It would be great to be able to change the font size of times in the forecast graph. 
I have a medium-size display and I'm using this card to show the weather forecast. The problem is that although I am able to change the font size of the labels in the chart, the same thing is not possible with the other texts in the card. This lack results in too small texts for medium-size dispaly.

**Comment by arturbalabanov** [comment]
I have a similar issue, I changed `labels_font_size` and that works great, however I wasn't able to change the font size of the time ticks (i.e. MON, TUE etc. for the daily forecast). There is a setting for the text colour of them (`chart_datetime_color`) but not the font size.

I took a brief look at the source code and it seems quite trivial to change that, I think adding the following snippet [here](https://github.com/mlamberts78/weather-chart-card/blob/master/src/main.js#L635):

```javascript
      font: {
        size: config.forecast.chart_text_size || config.forecast.labels_font_size,
      },
```

where `chart_ticks_text_size` is a new option. `labels_font_size` seems like a sensible default for it (and if adding a new option is more work than it's worth it, I'd be happy with just using `labels_font_size` instead).

I'd be happy to open a PR for this but I'm new to HomeAssistant in general and will need some guidance on best practices, how to test it etc.

@mlamberts78 what are your thoughts?
