### ISSUE TITLE
Days of the week not showing while casting card in DARK THEME to Google Nest Hub

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [mlamberts78/weather-chart-card#20]
**Describe the bug**
@mlamberts78 If i try to cast the weather card using the service "Google Cast: show dashboard view"  to my Google Nest Hub Devices IN DARK THEME it not shows the days of the week above the graph, If I open the same lovelace card on my PC in Opera it does show the days of the week (see pictures)

If I cast in light theme then it show the days in black color text, I assume the text not adjust to white color when using dark theme on Nest Hub

**To Reproduce**

**Expected behavior**
To show all of the card while casting to my Google Nest Hub Devices 

**Screenshots**

![1691084479854](https://github.com/mlamberts78/weather-chart-card/assets/97987488/f06eb892-5ec4-4242-8dd1-26db49f5cc05)
![1691084532027](https://github.com/mlamberts78/weather-chart-card/assets/97987488/d92e3444-7356-4b39-8e26-debf7e0c4305)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION: 1.6.5
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE:
 Home Assistant OS, 2023.8
 - OS: 10.4
 - Browser: Opera
 - Version:  100.0.4815.76

**Additional context**

**Comment by mlamberts78** [comment]
I don't have a Google nest hub myself, but I'll see if I can find the reason for this.

**Comment by smarthomefamilyverrips** [comment]
> I don't have a Google nest hub myself, but I'll see if I can find the reason for this.

@mlamberts78, Thanks! If you need any help with testing or more info then let me know

**Comment by mlamberts78** [comment]
@smarthomefamilyverrips, beta version **V1.8-dev.1** cointains an updated version of chart JS, can you test that version for me to see if it solves your problem on your Google nest device in dark mode?

In HACS you can redownload the card and select "Show beta versions"

**Comment by smarthomefamilyverrips** [comment]
> @smarthomefamilyverrips, beta version **V1.8-dev.1** cointains an updated version of chart JS, can you test that version for me to see if it solves your problem on your Google nest device in dark mode?
> 
> In HACS you can redownload the card and select "Show beta versions"

@mlamberts78 I will test and let you know as soon I get home! 👍

**Comment by smarthomefamilyverrips** [comment]
@mlamberts78 I did try the beta version but unfortunately still not see the days in darkmode.

**Comment by mlamberts78** [comment]
How do you cast to your Google nest hub?

**Comment by smarthomefamilyverrips** [comment]
@mlamberts78 I am using the cast.show_lovelace.view service

service: cast.show_lovelace_view
data:
  dashboard_path: lovelace
  entity_id: media_player.nesthubmax72cd_2
  view_path: test
enabled: true

**Comment by mlamberts78** [comment]
Can you have a look to this issue? https://github.com/home-assistant/core/issues/63213
Do you think it’s related?

**Comment by smarthomefamilyverrips** [comment]
@mlamberts78 it could be but did try to add the line to yaml of my dashboard want to cast but makes no difference.... but am not sure I added it correct

**Comment by smarthomefamilyverrips** [comment]
> Can you have a look to this issue? [home-assistant/core#63213](https://github.com/home-assistant/core/issues/63213) Do you think it’s related?

@mlamberts78 it could be but adding the line to theme in my dashboards settings yaml not changing anything, but I am not sure if I added it correctly 

theme:
  - ha-card-header-color: var(--primary-text-color)
title: Test
path: test
type: panel
subview: true
badges: []

**Comment by smarthomefamilyverrips** [comment]
I closed it by accident

**Comment by smarthomefamilyverrips** [comment]
@mlamberts78 if I change the theme in the nest hub max from dark to light and back to dark again and after add the line out of your referenced post #63213 then it works.  The only problem is it just works once then, as soon casting of dashboard stops and I cast it again I am back without days of week and need to do same steps again

My dashboard YAML

theme:
   ha-card-header-color: var(--primary-text-color)
title: Test
path: test
type: panel
subview: true
badges: []

**Comment by mlamberts78** [comment]
@smarthomefamilyverrips Please test version **1.8-dev.2**.
I did implement primary-text-color for the date / time text in the chart.

**Comment by smarthomefamilyverrips** [comment]
> @smarthomefamilyverrips Please test version **1.8-dev.2**. I did implement primary-text-color for the date / time text in the chart.

@mlamberts78 unfortunately that also did not work

**Comment by mlamberts78** [comment]
@smarthomefamilyverrips in your picture I see that the text color of the temperature labels also are in black, but still visible because of the white background (Which should also not be the case). There is not much I can do at this moment, it seems a problem Google Cast intergation not diplaying the right colors within the chart presented by chart.js.

**Comment by smarthomefamilyverrips** [comment]
@mlamberts78 I see that is to bad.... but would it be possible to add possibility to change text color (and size, font, etc.) same as in custom button card for example.... i set my text on custom button card white and it always stays white no matter what theme settings are used in Nest Hub or HA

**Comment by mlamberts78** [comment]
@smarthomefamilyverrips Sure will have a look to that option.

**Comment by smarthomefamilyverrips** [comment]
> @smarthomefamilyverrips Sure will have a look to that option. I guess you only want the option to change the days of the week font color? Because when also the labels change to white, they will not bereadable due to the white background.

To start would be nice to be days of the week first yes to at least be able to use your custom card for casting.... ultimately I think it will be a nice addition to have options to change text colors, sizes, fonts an so on available for all text on card.... for example I would like if the font size of the current temperature could be a bit bigger as it is relatively small  and poor visible from a low distance now on my Nest Hubs

**Comment by smarthomefamilyverrips** [comment]
@mlamberts78 maybe also can add function to change text field backgrounds colors, that also would solve my labels problem and I could set it to show white text on black background instead of black text on white background as it is now 👍

**Comment by mlamberts78** [comment]
Added the following configuration options which you can use:

```
current_temp_size:
forecast:
  chart_datetime_color:
```

**Comment by mlamberts78** [comment]
> > Added the following configuration options which you can use:
> > ```
> > current_temp_size:
> > forecast:
> >   chart_datetime_color:
> > ```
> 
> @mlamberts78 thank you... what format should I use to change color and size.... could you give a example perhaps? Thanks upfront!

You can use rgb, but also just words like black, white, red.

**Comment by smarthomefamilyverrips** [comment]
@mlamberts78 now I have like this but not changes color of days nor size of current temperature.... I do something wrong?

type: custom:weather-chart-card
            entity: weather.openweathermap
            show_main: true
            show_attributes: false
            show_time: true
            show_day: true
            show_date: true
            show_humidity: true
            show_pressure: true
            show_wind_direction: true
            show_wind_speed: true
            show_sun: true
            forecast:
              labels_font_size: '11'
              show_wind_forecast: false
              condition_icons: true
              round_temp: false
              chart_datetime_color: red
            current_temp_size: 20px
            units:
              pressure: hPa
              speed: km/h
            title: ''
            icons: ''
            temp: sensor.lumi_lumi_weather_temperature
            press: sensor.lumi_lumi_weather_pressure
            humid: sensor.lumi_lumi_weather_humidity
            uv: ''

**Comment by mlamberts78** [comment]
Did you download the latest version V1.7.1?

**Comment by smarthomefamilyverrips** [comment]
> Did you download the latest version V1.7.1?

Oops no I did got notification this morning of a update and did run that, did not see was a new version, srorry.... all works now as should... when home I will try if by forcing font color to white it will show days of week on my Nest Hub while casting.... I will keep you posted, thanks so far! 👍

**Comment by smarthomefamilyverrips** [comment]
@mlamberts78 I did test to force color of days to white and now is visible on my Nest Hub 👍 ... also it helps that I can change font size of outside temperature only doing this put card out of it original size and pushes other cards out of my dashboard view on my Nest Hub, it would be nice if could hide the text under the outside temperature that describe current weather conditions (for example "sunny") so that the free space is available for showing outside temperature in bigger font without making the overal card size bigger... I really like the card a lot but I think for me and for others also would be a big plus if the seperate elements within the card are also customizable (show, hide, size, color, background etc.) If you would be able to do this it will make the difference to being great and perfect to my opinion.... but for now i would had been helped if i could also hide the weather conditions text under the outside temperature 🥇

**Comment by mlamberts78** [comment]
@smarthomefamilyverrips , Added the option to hide the current weather condition in **V1.7.2** to fix your card size.
I will add more customizable options in the next releases.

**Comment by smarthomefamilyverrips** [comment]
> @smarthomefamilyverrips , Added the option to hide the current weather condition in **V1.7.2** to fix your card size. I will add more customizable options in the next releases.

@mlamberts78 that did solve my problem, and can use it now as you can see on picture below, am looking forward to have more options to customize, for example what still kind of is off for my use case is that weather condition and forcast icons are blue now and date/time greyish for me would be nicer if these also would be white..... also personal i really would like if the weather condition/forcast icons would be animated, for example same as in "custom:platinum-weather-card" personal I like that those icons have colors and movements .... but for now I am happy I can use your card like this and look forward to future updates with new options and improvements 👍 .... Thank you for the work you put in !!!

![1691914480726](https://github.com/mlamberts78/weather-chart-card/assets/97987488/a461c874-2360-463b-bd75-11d1d6311880)
