### ISSUE TITLE
"undefined.svg" or generic fallback if provider has no data

### ISSUE THREAD

**Issue by majorsl** [mlamberts78/weather-chart-card#207]
**Describe the bug**
Rarely, but on occasion I've seen my provider return an "undefined" for a condition icon.  This results in the card displaying a broken image.

**To Reproduce**
Just wait for a provider to provide an unknown or undefined condition.

**Expected behavior**
If possible, the card should have some logic to fallback to a generic icon in the event a provider is missing something.  I've seen other cards use an "undefined.svg" for this situation.

**Desktop (please complete the following information):**
 - 2.4.7
 - HA Docker 2024.7.1
 - OS: Docker
 - Edge/Chrome
 - 126.0

**Comment by Eisbaer2** [comment]
Same here

**Comment by MHerbst** [comment]
I have got the same problem in combination with the DWD weather integration that does not provide a value for the current day.
In this case the card tries to load this icon: https://cdn.jsdelivr.net/gh/mlamberts78/weather-chart-card/dist/icons/undefined.svg that does not exist.
