### ISSUE TITLE
after adding a weather map, Lovelace stops working

### ISSUE THREAD

**Issue by Vladd1980** [mlamberts78/weather-chart-card#210]
after adding a weather map, Lovelace stops working. in the logs I see this information: 

Uncaught error from Chrome 126.0.0.0 on Linux x86_64 TypeError: t.reduce is not a function extractMediaQueries (src/panels/lovelace/common/validate-condition.ts:317:20) onChange (src/panels/lovelace/common/validate-condition.ts:332:23) this._clearMediaQueries (src/panels/lovelace/cards/hui-card.ts:209:6) connectedCallback (src/panels/lovelace/cards/hui-card.ts:60:9) apply (src/scoped-custom-element-registry.js:248:41) _addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:263:15) Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:236:11)
Uncaught error from Chrome 126.0.0.0 on Linux x86_64 TypeError: t.reduce is not a function extractMediaQueries (src/panels/lovelace/common/validate-condition.ts:317:20) onChange (src/panels/lovelace/common/validate-condition.ts:332:23) this._clearMediaQueries (src/panels/lovelace/cards/hui-card.ts:209:6) connectedCallback (src/panels/lovelace/cards/hui-card.ts:60:9) apply (src/scoped-custom-element-registry.js:248:41) _addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:255:15) Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:236:11)
Uncaught error from Chrome WebView 126.0.6478.134 on Android 14 ReferenceError: drawChartOncePerHour is not defined /hacsfiles/weather-chart-card/weather-chart-card.js:18226:7
Uncaught error from Chrome WebView 126.0.6478.134 on Android 14 TypeError: t.every is not a function conditions (src/panels/lovelace/common/validate-condition.ts:169:20) _updateVisibility (src/panels/lovelace/cards/hui-card.ts:230:25) fireEvent (src/panels/lovelace/cards/hui-card.ts:135:9) ev.stopPropagation (src/panels/lovelace/cards/hui-card.ts:127:13) dispatchEvent (src/common/dom/fire_event.ts:76:7) tag.includes (src/panels/lovelace/create-element/create-element-base.ts:136:14)
Uncaught error from Chrome 126.0.0.0 on Linux x86_64 TypeError: t.every is not a function conditions (src/panels/lovelace/common/validate-condition.ts:169:20) _updateVisibility (src/panels/lovelace/cards/hui-card.ts:230:25) fireEvent (src/panels/lovelace/cards/hui-card.ts:135:9) ev.stopPropagation (src/panels/lovelace/cards/hui-card.ts:127:13) dispatchEvent (src/common/dom/fire_event.ts:76:7) tag.includes (src/panels/lovelace/create-element/create-element-base.ts:136:14)

home assistant version: 2024.7.3
weather chsrt card version: 2.4.7

**Comment by Pelvis1416** [comment]
I am experiencing similar issues and would like to note that I am running a Dockerized version of HO

**Comment by BartVPL** [comment]
same issue here after upgrade do HA core - anyone know how to fix that?

**Comment by Vladd1980** [comment]
in my opinion this is due to the number of entities. As soon as I connect more than 9 entities, Lovelace stops working
![image](https://github.com/user-attachments/assets/2a03708f-9cb2-4677-88f7-27f8547d429d)

**Comment by Pelvis1416** [comment]
I have tested it just now, and Lovelace still does not work, even when configured with 9 entities.

**Comment by BartVPL** [comment]
Seems to work I've deleted the chart from lovelace card completely and created new from the scratch no error so far.
