### ISSUE TITLE
Add Offset property for customize time range

### ISSUE THREAD

**Issue by MelleD** [mlamberts78/weather-chart-card#219]
**Is your feature request related to a problem? Please describe.**
I would like to show the hourly weather for tomorrow e.g. beginning 9am. That I can see the hourly forecast for tomorrow, that i can make better decision to organize trips.

**Describe the solution you'd like**
A property (e.g offset) should solve the issue like "Number of forecast segments to offset from start"

**Comment by mathieucarbou** [comment]
+1 for this feature.

A lot of weather cards have an offset feature to skip the N first hours.

This is required to display the cards in a column where we are limited to only 5-7 hours per widget, so a solution is to add twice this same widget, first one displaying the next 7 hours and the second one displaying the next 7 hours after. These 2 widgets allow a column view of a while day (+14 hours).

@mlamberts78
