### ISSUE TITLE
Add possibility to change font sizes and colors

### ISSUE THREAD

**Issue by andy-arbeit** [mlamberts78/weather-chart-card#233]
**Is your feature request related to a problem? Please describe.**
I would like to change some font sizes and colors, especially in the chart-container (size of shown day). I cannot solve this with css.

**Describe the solution you'd like**
Can you add the possibility to change font sizes of the main and the chart-container? Alternatively I would like to get the css-object to change it.

**Additional context**

**Comment by fir3drag0n** [comment]
is there a solution yet in order to change the font colors, in particular the chart container and the weekdays (Mon, Tues,...)?
