### ISSUE TITLE
Card Empty, "please, check your weather entity

### ISSUE THREAD

**Issue by mpkoslovsky** [mlamberts78/weather-chart-card#236]
**Describe the bug**
When a new custom card is added: Weather Chart Card, you cannot see the preview image on the right side.
![image](https://github.com/user-attachments/assets/ed8d0445-f30d-413e-a799-61712f234950)

**To Reproduce**
When performing the configuration pointing to the current entity, the preview is not displayed
![image](https://github.com/user-attachments/assets/302ba1bb-5edf-4b1b-bc70-6e46437c1ade)

After completing the configuration, the card remains empty on the dashboard
![image](https://github.com/user-attachments/assets/a0681459-fc1b-4044-92d3-662660282703)

I did the same process on a new instance of Home Assistant and it worked. I need to understand what is happening in this case that is not working as expected.

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE (e.g.  2024.8.3)
 - Browser  chrome
 - Version  128

**Comment by mpkoslovsky** [comment]
Now when I try to configure I receive this message
![image](https://github.com/user-attachments/assets/c8e8e7d7-fc7b-4749-8021-70ae7f473339)

**Comment by wyclef77** [comment]
Same issue here both in desktop and companion app (Iphone). 
Not sure if there is a fix?

**Comment by mpkoslovsky** [comment]
I haven't been able to solve it yet.
