### ISSUE TITLE
Cards Not Showing In Dashboard Unless I Click On The Pencil (To Edit Dashboard)

### ISSUE THREAD

**Issue by ColtonYYZ** [mlamberts78/weather-chart-card#237]
**Describe the bug**
After creating the card and filling in all the parameters, the weather card won't show in the dashboard unless I click on the pencil to edit the dashboard. It then will show in the edit page, and then in the dashboard. Sometimes it doesn't load fully either.

**To Reproduce**
1. Create card in dashboard
2. Exit out of the edit page
3. Cards do not show
4. Click pencil
5. Cards show in edit page as well as in the dashboard after you exit the edit page

**Expected behavior**
It should show the cards in the dashboard without any intervention

**Screenshots**
![missing](https://github.com/user-attachments/assets/134e2483-33f8-4483-9d2f-78b2728d1be4)
![missing-found](https://github.com/user-attachments/assets/6ab7b085-7225-4f01-a231-57123c18dae7)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION:  V2.4.9
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE:  Core: 2024.8.3
 - OS: Windows (though my android tablets experience the same thing)
 - Browser: Chrome
 - Version 128.0.6613.85 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by mlamberts78** [comment]
This is not a weather map issue, please check your dashboard settings/visibility.

**Comment by dxmnkd316** [comment]
This happens to me.  The cause in my case has always been incorrectly formatted sensor data.  Always.  Usually it's something like attributes being called that don't exist or are empty.
