### ISSUE TITLE
Custom icons not showing properly in Forecast?

### ISSUE THREAD

**Issue by berkavil** [mlamberts78/weather-chart-card#247]
Hallo, when using my custom icons set ("custom icons" folder option in the card setup and disabled original animations...)
- I see the actual icon in the up-left corner => OK
- but the forecast icons are not shown - just broken img thumbs as can be seen on pic attached:
![image](https://github.com/user-attachments/assets/4784c09a-413b-40be-8afa-71f5f8041b2f)

any clue please, what am I doing wrong?

**Comment by berkavil** [comment]
I have all custom icons in the same path ("/www/weathericons/") - and all file names are as recommended at the example in the documantation...
Tried different options in the card setting, but I can only see the original animated, original not animated or empty pics (broken) so far...
thanks for any help

**Comment by dxmnkd316** [comment]
Right click on the broken image and see what URL it is trying to point at.  This should provide some insight on where the card is looking for the images and whether that matches the actual storage location.

**Comment by berkavil** [comment]
Yes, I did that, but not helping, since the path for the pics ("/local/weathericons/") seem to be OK... if it wasn't correct it wouldn't show the correct icon in the up-left corner, am I right? I gues that the problem might be with the "-" in some pic names ... e.g., "partlycloudy-day.svg"  (?) is it some special "-" or maybe language version sensitive letter? 
(I am waiting until it's "Sunny" outside to confirm that diagnose :-)...
W.

**Comment by berkavil** [comment]
heh - I just wrote and checked the weather card a bit later... here it comes:
![image](https://github.com/user-attachments/assets/32544d24-7570-4013-ad00-2a23e5521a21)

**Comment by berkavil** [comment]
I guess I will clear browser history thoroughly and rename all files with EN keyboard and we will see...

**Comment by rudizl** [comment]
left click on the empty image and choose Inspect or something similar to check the name. The naming convention is old and not full. 
![image](https://github.com/user-attachments/assets/435f02ad-6764-467d-990f-7f5a64cd39e5)

**Comment by mlamberts78** [comment]
You can find the right naming in the readme and here: https://github.com/mlamberts78/weather-chart-card/blob/master/src/const.js#L24
