### ISSUE TITLE
Allow user to select how many future forecasts to show

### ISSUE THREAD

**Issue by cmerkle** [mlamberts78/weather-chart-card#30]
**Is your feature request related to a problem? Please describe.**

I do not currently understand how the card decides how many future forecasts to show. I have a pirate weather entity that contains hourly forecasts for the next 7 days, however the card is only displaying the next 4 hours. I want to be able to customize this, to be able to show the forecast for day the next 12 hours, but I don't see a way to do this at the moment.  

**Describe the solution you'd like**

An option that allows the user to select how many days/hours into the future they would like to display in the forecast chart. The  user should also be able to select an interval, I.e. show the forecast every 2 hours for the next 12 hours. 

![image](https://github.com/mlamberts78/weather-chart-card/assets/33108196/a4156522-609c-4173-aead-bfb928906b80)

![image](https://github.com/mlamberts78/weather-chart-card/assets/33108196/bc0e00ac-5b2e-42b4-a1a7-c65b1c6dfda0)

**Comment by mlamberts78** [comment]
The amount of displayed forecasts are based on the size of the card, when a user is able to change it, it will mess up the card and the forecasts will be overlapping.
Will not be implemented.
