### ISSUE TITLE
Does not work with the Weather Forecast (No Attributes)

### ISSUE THREAD

**Issue by briis** [mlamberts78/weather-chart-card#31]
**Describe the bug**
If you have a Weather Entity, that follows the new Weather Entity description, is does not have the forecast as attributes anymore, and it will then not work with this card. The built-in Weather Card, works fine, even with an entity as described above.

**Expected behavior**
Display my data, instead I get a 'please check your weather entity'

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION 1.8.1
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE: HAOS V2023.10.1

**Comment by mlamberts78** [comment]
Fixed in version V2.0.
Legacy method is not supported anymore

**Comment by briis** [comment]
Thanks for this. Unfortunately it does not work completely. It seems like the property `forecast` still needs to be defined in the weather entity, or the card will throw this error:

````
TypeError: Cannot read properties of null (reading 'getContext')
WeatherChartCard.drawChart (/local/weather-chart-card.js:17391:62)
Object.callback (/local/weather-chart-card.js:17186:10)
callback (node_modules/home-assistant-js-websocket/dist/connection.js:23:33)
forEach (node_modules/home-assistant-js-websocket/dist/connection.js:15:25)
````
If I test against the default Met.No integration, your card works fine, but this card still supplies the Forecast attributes, and at the same time supports get_forecast. I have a Weather Integration where the Forecast attributes are complete removed, and this throws the above error. That same integration work perfectly with the built-in weather card.

**Comment by mlamberts78** [comment]
@briis, thanks for the feedback. can you tell me which weather integration you are using? Then I can test and fix the issue for you.

**Comment by briis** [comment]
I have tested against this one https://github.com/briis/visualcrossing which is a Custom Integration I wrote myself. If you follow the instructions, you can get a Free Api key to test with. 
As written above, this integration works fine with the standard Weather Card and the service `get_forecast` is also working.

If I add the below code to the file `weather.py` your card works. But that piece of code generates the Forecast Attributes which I guess should not be needed. As soon as I remove this again, it does not work. If you look at the Core Weather Integration called `met`, which is the default weather entity installed, it also still has the forecast attribute. I assume that will disappear also from there in 2024.3.

Hope this helps.

```python

    @property
    def forecast(self) -> list[Forecast] | None:
        """Return the forecast array."""
        return self._forecast(False)
````

**Comment by Revyen** [comment]
I have the same issue. Using the Deutsche Wetterdienst HACS integration https://github.com/FL550/dwd_weather. The Home Assistant Weather forecast works fine.

**Comment by aldets** [comment]
I'm using this > https://www.home-assistant.io/integrations/accuweather
Getting the same errors in the log and the card won't show the graph. Looking at the States in Developer Tools the "weather.home" entity has the attribute "forecast".

**Comment by mlamberts78** [comment]
V2.0.1 is released, this should fix your issue that property forecast should be present.

**Comment by briis** [comment]
I can confirm that this now works. Thank @mlamberts78

**Comment by Revyen** [comment]
Works with Deutsche Wetterdienst too, thanks @mlamberts78
