### ISSUE TITLE
REQUEST: Add Bft as windspeed unit of measure

### ISSUE THREAD

**Issue by MarcoGos** [mlamberts78/weather-chart-card#4]
First of all thank you for taking over this weather card.

My request is, can you add the Beaufort scale as windspeed?

See https://en.wikipedia.org/wiki/Beaufort_scale for more info.

Showing the Bft value (bottom row of the card) should be something like '<the arrow>' and 'NW 3' as text for a northwesterly wind with force 3 Bft.

**Comment by mlamberts78** [comment]
Hi Marco, I like to keep the presentation of km/h, m/s and bft in the same format, is this ok for you?
![bft](https://github.com/mlamberts78/weather-chart-card/assets/93537082/73d91666-1b4f-46b0-bd8b-cdc41d8356b8)

**Comment by MarcoGos** [comment]
Hi @mlamberts78, that perfectly fine with me. It looks awesome. Thank you.
