### ISSUE TITLE
Customize Time Display on Hourly Forecast Graph?

### ISSUE THREAD

**Issue by mlamberts78** [mlamberts78/weather-chart-card#45]
### Discussed in https://github.com/mlamberts78/weather-chart-card/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **christopherdopp** November 12, 2023</sup>
First of all, thank you for creating this fork with support for the new weather changes in the latest Home Asisstant!

I have a small feature request:

When showing the hourly forecast the time values for each column of the graph are in 24 hour format. I would prefer to have an option for a 12 hour format with AM/PM. 

_Would you consider adding an option to customize the time format? Perhaps even better, utilize the format  of the browsers locale setting? If you make this change, consider adding a similar configuration for  the day of week format._ (Fri, Sat, F, S, Friday, Saturday, etc.) I know there will be size constraints for some options, but flexibility would be great.

Thank You.</div>

**Comment by mlamberts78** [comment]
This enhancement will be included in next release.

**Comment by christopherdopp** [comment]
I finally got a chance to try the new version. It looks great. Thanks!
