### ISSUE TITLE
A few more alternate entities

### ISSUE THREAD

**Issue by rudizl** [mlamberts78/weather-chart-card#52]
I'm using the card for a few weeks, but since that time it's getting better and better. So thank you for that.

There are a few things that I'm missing:
1. Wind Gust in alternate entities.
2.  Rain rate in alternate entities.
3.  Feels like temperature somewhere below the real temp, and again with possibility to add it as alternate.
4.  and something like local observation time (last updated)

Thanks again for your good work.

**Comment by mlamberts78** [comment]
Thanks, happy to hear you like the card! 
Will have a look to your requests and include it in one of the next releases.

**Comment by stomko11** [comment]
i see v.2.2.4 had some fixes regarding feels like temperature. i added sensor for feels like temperature, but i am not seeing it in the card. Where is this supposed to be displayed?

**Comment by mlamberts78** [comment]
> i see v.2.2.4 had some fixes regarding feels like temperature. i added sensor for feels like temperature, but i am not seeing it in the card. Where is this supposed to be displayed?

When you add a sensor for the feels like temperature, in the main settings a new switch will appear. toggle that switch twice (off, on again) and you should see the feel like temperature.

**Comment by stomko11** [comment]
No, the toggle does not show up. I tried:
```
feels_like: sensor.real_feel
```
as well as:
```
feels_like: sensor.real_feel
show_feels_like: true
```

**Comment by rudizl** [comment]
It works for me as expected.
![1](https://github.com/mlamberts78/weather-chart-card/assets/5582186/d27c419e-51f5-43a4-9354-9703aec13b46)
![2](https://github.com/mlamberts78/weather-chart-card/assets/5582186/12dbec1f-e995-4dcd-a0a8-0e1059234492)
![3](https://github.com/mlamberts78/weather-chart-card/assets/5582186/8d1695a6-904d-461b-9f97-be9decf24e4e)

**Comment by stomko11** [comment]
I have re-downloaded same version from HACS and now it shows up.
