### ISSUE TITLE
Weather Chart Card incompatible with HA 2023.12.1

### ISSUE THREAD

**Issue by Roving-Ronin** [mlamberts78/weather-chart-card#55]
**Describe the bug**
Weather Chart Card is incompartible with HA 2023.12.1, after HA upgrade the card fails to load with error "Custom element doesn't exist: weather-chart-card" being shown. 
Attempting to add a new copy of this card to a view, fails to show the card as being installed / visible when you enter its name into HACS to filter/show it from the list of available cards. 

**To Reproduce**

Installed HA 2023.12.1 and reloaded screen. Also uninstalled the card then reinstalled, still not showing in HA as a card when you search for it in the list of cards and attempt to add it to a view. Existing instance of the card also fails to load.

**Expected behavior**
Card to load as per normal.

**Screenshots**
Existing Card fails to load:
![image](https://github.com/mlamberts78/weather-chart-card/assets/108674933/b28ff4bc-0e55-449c-9412-64b24fc2f906)

Try to add Weather Chart Card and not found (even though installed and un/reinstalled).
![image](https://github.com/mlamberts78/weather-chart-card/assets/108674933/7bdde205-30a4-419a-9f09-8dbb68ab8373)

**Desktop (please complete the following information):**
 - Card v2.2.2
 - HOME ASSISTANT VERSION 2023.12.1 managed install on dedicated Lenovo TinyPC
    - Core 2023.12.1
    - Supervisor 2023.11.6
    - Operating System 11.2
    - Frontend 20231208.2
 - Browser - Firefox v119.0 / Chrome v119.0.6045.161 (Official Build) (64-bit)

**Additional context**

**Comment by mlamberts78** [comment]
I’m running 2023.12.1 and have no issue with the card. 
Seems like there is an issue with the source in your installation for the card?
can you try the following?

Go to: 
Settings - Dashboards - 3 dots on right top corner - Resources
Then look for the weather-chart-card line, open it and select delete.

Then go to hacs and remove the card and download it again.

**Comment by Roving-Ronin** [comment]
Hi @mlamberts78,

I've removed the card in HACS and reinstalled (multiple times), and no luck.
I've removed the card from my dash and from HA, then also custom resource URL, then rebooted HA, added the URL back into HACS, and attempted to reinstalled the card in HACS. 

Below is after rebooting HA, then going into HACS and reinstalling the card, then going to my dash and searching for the card to add it back to the dash. Once again, even though the card is installed, it fails to even appear in the list of cards available:

![image](https://github.com/mlamberts78/weather-chart-card/assets/108674933/e5771b4a-2052-4060-b882-d868bb87673e)


Rebooted HA again and still fails to even appear in the list of available cards, even though it is installed (as per below):

![image](https://github.com/mlamberts78/weather-chart-card/assets/108674933/ee03d1bf-03e6-4352-96d3-cb6cefc1966c)

**Comment by kyselyna** [comment]
I have the same problem,.. I noticed that sometimes the card works and sometimes not, I see the same problem with the "sunsync-power-flow-card" It's strange that when the "Weather Chart Card" doesn't work the other card "sunsync-power- flow-card" work well. and vice versa, when the "sunsync-power-flow-card" card works, the "Weather Chart Card" does not work again

**Comment by mlamberts78** [comment]
I saw this problem also with other cards (Like LG TV remote card). At the moment I don't think this has something to do with the card and there is nothing I can change about it. It looks like a general HACS/HA issue.

**Comment by jata1** [comment]
Hello and thanks @mlamberts78 for the work you are doing on this card. 

I was using the older version (from 3 yrs ago) but it stopped working recently. I thought because of the changes that have been made to forecast entities in HA although think the impact is not until April 2024.

So I have clean installed your version but I have the same issue as others in that the card is not available when you try to add to a dashboard and if you set it up manually it does not work either.

I think I agree it is a general issue with HACS/HA but do you know if anything is being done to resolve this?

**Comment by jata1** [comment]
today it just started working. Maybe related to a HACS update? I have not made any changes

**Comment by kyselyna** [comment]
still does not work :(

Weather Chart Card   V2.2.6
sunsynk-power-flow-card   V4.11.2
HACS    V1.34.0
HA core  2024.1.6
HA supervisor 2024.01.1
HA Operating System  11.5

Raspberry Pi 4 8GB 


![Snímek obrazovky 2024-02-06 111041](https://github.com/mlamberts78/weather-chart-card/assets/113242963/63da5fb8-6cd1-455f-a91b-64db34af2362)
![Snímek obrazovky 2024-02-06 110914](https://github.com/mlamberts78/weather-chart-card/assets/113242963/b5ca5d21-9275-403d-b0bb-85289dec2e68)
