### ISSUE TITLE
precipitation_probability and precipitation

### ISSUE THREAD

**Issue by pipacsba** [mlamberts78/weather-chart-card#56]
**Is your feature request related to a problem? Please describe.**
I would like to see both the precipitation and precipitation_probability at the same time.

**Describe the solution you'd like**
For precipitation_probability I do not need bar (or any visual information), simple text is perfect. (e.g. selectable to replace wind forecast?)

**Comment by hcoohb** [comment]
Having this ability so see both at the same time would be amazing!
Or maybe at least having both in the tooltip ?

Thanks for your work on maintaining this card btw!

**Comment by jeffjensen** [comment]
Me too!  I'd like to have both Precipitation % and Rainfall values, not just one of them.  If can't represent both, then how about the tooltip always displays both and the main display has the chosen one.

**Comment by tigers75** [comment]
I second this request: the bar for probability is not much useful, I'd prefer to have at a glance the precipitation, but still see the probability.
Having a tall bar meaning there's 90% chance of a 1 mm precipitation or a small bar for a 60% of a 15 mm precipitation is misleading for a chart that's intended to give a quick overview. I'd like to have the bar as tall as the precipitation forecast maybe with a small number on top representing the precipitation, with the probability as a number underneath, or viceversa.

**Comment by jeffjensen** [comment]
Works great, thank you!

**Comment by pipacsba** [comment]
Thank you!
