### ISSUE TITLE
Ability to choose language

### ISSUE THREAD

**Issue by szatan81** [mlamberts78/weather-chart-card#57]
It would be great if we could use language variable to use other language than set in HA.
Thanks for great work.

**Comment by mr-aleks** [comment]
Why are language settings not fully applied?
![Снимок экрана 2024-01-08 170501](https://github.com/mlamberts78/weather-chart-card/assets/23143866/d98f3faf-7cf2-4af2-8b23-1da227543ee4)

**Comment by mlamberts78** [comment]
> Why are language settings not fully applied? ![Снимок экрана 2024-01-08 170501](https://private-user-images.githubusercontent.com/23143866/294926921-d98f3faf-7cf2-4af2-8b23-1da227543ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3Mjc1NjgsIm5iZiI6MTcwNDcyNzI2OCwicGF0aCI6Ii8yMzE0Mzg2Ni8yOTQ5MjY5MjEtZDk4ZjNmYWYtN2NmMi00YWYyLThiMjMtMWRhMjI3NTQzZWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE1MjEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMWZmMzlmODcxYzYzMzM1ZWRkYzIxMDIwMTEzODQzZTUzZGZjODg2NzE4OWY0NjA5NzI3MjkxOGE3NDkxMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oO88pAtYIfyAuoIhixO58B8wtd4DPX_XaA65PpitQHo)

You are correct , will have a look to it and correct it in a next version.
