### ISSUE TITLE
invalid date

### ISSUE THREAD

**Issue by geertvercamer** [mlamberts78/weather-chart-card#6]
Hi,

love the chart!
but when hovering over the temperature values, I get an 'invalid date' in the label:
![image](https://github.com/mlamberts78/weather-chart-card/assets/11328101/da7e8d01-90b4-433d-a0c2-eaecef6bf394)
(it doesn't matter whether I hover over min, max, rain, ...)

I have my own weather station, uploading data to Wunderground and using the WUndergroudpws integration to show the weather data in HA.

Thanks!

**Comment by mlamberts78** [comment]
Unfortunately I don’t have a personal weather station, can you provide me a snapshot of your weather entity attributes output?

Developer tools - States:
Filer on your weather entity and copy all info from the attributes. It should contain forecast.

**Comment by geertvercamer** [comment]
OK, I don't see any dates there.
All forecast attributes are
![image](https://github.com/mlamberts78/weather-chart-card/assets/11328101/1b3ddce8-84dc-4c3e-a0db-c89b69386325)
they all are named like
sensor.STATIONID_forecast_ITEM_0d
sensor.STATIONID_forecast_ITEM_1n
sensor.STATIONID_forecast_ITEM_2d
sensor.STATIONID_forecast_ITEM_3n
sensor.STATIONID_forecast_ITEM_4d
sensor.STATIONID_forecast_ITEM_5n
sensor.STATIONID_forecast_ITEM_6d
sensor.STATIONID_forecast_ITEM_7n
sensor.STATIONID_forecast_ITEM_8d
sensor.STATIONID_forecast_ITEM_9n
where ITEM is summary or temperature
1-9 is a sequence, n/d stand for night/day/

sensor.STATIONID_forecast_temperature_1n is temperature forecast tonight
sensor.STATIONID_forecast_temperature_2d is temperature forecast tomorrow day
sensor.STATIONID_forecast_temperature_3n is temperature forecast tomorrow night
sensor.STATIONID_forecast_temperature_4d is temperature forecast the day after tomorrow day (friendly name seems to change to have the day (Friday) )
...

**Comment by mlamberts78** [comment]
The data displayed in the chart is not from the provided sensors, can you check in the card configuration which entity is used and provide the attributes data of that entity?

**Comment by geertvercamer** [comment]
ok, sorry, my bad. The entity is weather.STATIONID, in this case weather.izonne25
attributes:
temperature: 18.1
temperature_unit: °C
humidity: 58
pressure: 1007.01
pressure_unit: hPa
wind_bearing: 354
wind_speed: 0.3
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- condition: rainy
  precipitation: 17.55
  precipitation_probability: 100
  temperature: 23
  templow: 12
  datetime: 1690347600000
  wind_bearing: SSW
  wind_speed: 18
- condition: rainy
  precipitation: 6.48
  precipitation_probability: 98
  temperature: 19
  templow: 15
  datetime: 1690434000000
  wind_bearing: SW
  wind_speed: 27
- condition: rainy
  precipitation: 0.3
  precipitation_probability: 47
  temperature: 23
  templow: 16
  datetime: 1690520400000
  wind_bearing: SW
  wind_speed: 18
- condition: rainy
  precipitation: 1.84
  precipitation_probability: 73
  temperature: 22
  templow: 15
  datetime: 1690606800000
  wind_bearing: SW
  wind_speed: 26
- condition: partlycloudy
  precipitation: 0
  precipitation_probability: 24
  temperature: 21
  templow: 14
  datetime: 1690693200000
  wind_bearing: WSW
  wind_speed: 32

**Comment by mlamberts78** [comment]
The problem is that the datetime attribute format is not correct, according the official Home Assistant developers documentation it should be **UTC Date time in RFC 3339** format: https://developers.home-assistant.io/docs/core/entity/weather/

The best you can do is create a new issue in the [Home-Assistant-wundergroundpws](https://github.com/cytech/Home-Assistant-wundergroundpws) repository pointing them to this issue and have them passing the correct format to the datetime attribute for the forecast.

**Comment by geertvercamer** [comment]
Ok, will do. Thanks for your time and effort!
