### ISSUE TITLE
Wind speed shows NaN km/h 

### ISSUE THREAD

**Issue by iamdabe** [mlamberts78/weather-chart-card#61]
**Describe the bug**
Underneath the chart and conditions in the wind speed detail panel the wind is shown as 'NaN km/h' for all days. It' bizarre because on the main card attribute panel it displays fine.

I'm using the meteofrance integration.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add the weather-chart-card by mlamberts78 to lovelace dashboard with default settings.

**Expected behaviour**
Expected the wind speed to be shown as returned by the weather object.

**Screenshots**
![image](https://github.com/mlamberts78/weather-chart-card/assets/11339405/904b13f6-015d-4c36-baae-8145e90f9950)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION v2.2.3
 - Home Assistant Core 2023.12.2, Frontend 20231208.2
 - OS: Windows 11 23H2 22631.2861
 - Browser: Chrome v120.0.6099.131

**Additional context**

**Comment by mlamberts78** [comment]
Checked, but the problem is with the meteofrance integration, it is not providing the wind_speed in the forecast data:

forecast:
  - datetime: "2024-01-09T01:00:00+01:00"
    condition: cloudy
    temperature: -0.1
    templow: -1.8
    precipitation: 0
    humidity: 75
  - datetime: "2024-01-10T01:00:00+01:00"
    condition: cloudy
    temperature: 1.4
    templow: -1.9
    precipitation: 0.2
    humidity: 80
  - datetime: "2024-01-11T01:00:00+01:00"
    condition: sunny
    temperature: 2
    templow: -1.8
    precipitation: 0
    humidity: 75
  - datetime: "2024-01-12T01:00:00+01:00"
    condition: sunny
    temperature: 3.9
    templow: -0.6
    precipitation: 0
    humidity: 95
