### ISSUE TITLE
Add span option for hourly forecast

### ISSUE THREAD

**Issue by GodMod** [mlamberts78/weather-chart-card#62]
**Is your feature request related to a problem? Please describe.**
In the morning, I wan't to know what the day brings. Means: how will be the temperature and the rain for the next 10-12 hours.
When choosing the hourly forecast, every next hour is shown. So when looking at 8 am at the graph, I see 8,9,10 etc., but only until 14pm. 

**Describe the solution you'd like**
The graph should only show every second/third etc. hour, e.g. 8am, 10am, 12am, 14pm, 16pm etc.

**Additional context**
-

**Comment by mlamberts78** [comment]
The weather card only shows the data that comes in from the weather integration. If you want a 2 or 3 hourly forecast, you will have to submit a request to your weather integration developer. For example, OpenWeatherMap provides the option to display a 3-hourly forecast.
