### ISSUE TITLE
Weather Chart Card not showing daily forecast...hourly works fine.

### ISSUE THREAD

**Issue by MichaelStruck** [mlamberts78/weather-chart-card#69]
**Describe the bug**
After Installation, installed this HACS item. Idea is great! However the daily forecast does not happen to work. Hourly works great. but can not get the daily forecast to display. Reboot HA and the same result. Using another weather card (and the forecase is being provided by NWS (direct from HA)

**To Reproduce**
Install item from HACS
Attempt to add the card to the dashboard
See nothing on daily forecast. Toggle, hourly works fine. 

**Expected behavior**
Expect to see daily forecasrts.

**Screenshots**

**Desktop (please complete the following information):**
 - Using 2.2.5
 - HA: 2024.1.6
 - OS: 11.,5
 - Browser: Edge (windows 11)
 - Version:121

**Additional context**
![image](https://github.com/mlamberts78/weather-chart-card/assets/11378005/9911ae75-25e1-4d10-b2f9-e77ad54f37c3)

**Comment by MichaelStruck** [comment]
Here is the data presented by NWS...Could it be that the twice daily heading has anything to do with this:
![image](https://github.com/mlamberts78/weather-chart-card/assets/11378005/8f5c25fb-2ae9-4ebf-ad0c-4fbcc760d23c)

Also, here is an error when pulling daily info:
![image](https://github.com/mlamberts78/weather-chart-card/assets/11378005/8ca4c84a-14f1-475d-8d84-0244681bf1fb)


Finally, here is the JSON of the output of twice daily:
weather.seattle:
  forecast:
    - detailed_description: >-
        A chance of rain. Cloudy, with a high near 47. North northwest wind 7 to
        13 mph. Chance of precipitation is 40%. New rainfall amounts less than a
        tenth of an inch possible.
      datetime: "2024-02-05T08:00:00-08:00"
      precipitation_probability: 40
      is_daytime: true
      condition: rainy
      wind_bearing: 337.5
      temperature: 47
      dew_point: 40
      wind_speed: 10
      humidity: 78
    - detailed_description: >-
        A chance of rain. Cloudy, with a low around 44. North northwest wind 2
        to 7 mph. Chance of precipitation is 40%. New rainfall amounts less than
        a tenth of an inch possible.
      datetime: "2024-02-05T18:00:00-08:00"
      precipitation_probability: 40
      is_daytime: false
      condition: rainy
      wind_bearing: 337.5
      temperature: 44
      dew_point: 42
      wind_speed: 4.5
      humidity: 88
    - detailed_description: >-
        A slight chance of rain before 10am. Mostly cloudy, with a high near 48.
        South southeast wind 0 to 5 mph. Chance of precipitation is 20%. New
        rainfall amounts less than a tenth of an inch possible.
      datetime: "2024-02-06T06:00:00-08:00"
      precipitation_probability: 20
      is_daytime: true
      condition: rainy
      wind_bearing: 157.5
      temperature: 48
      dew_point: 42
      wind_speed: 2.5
      humidity: 88
    - detailed_description: >-
        A chance of rain after 10pm. Mostly cloudy, with a low around 41. South
        southeast wind around 5 mph. Chance of precipitation is 40%.
      datetime: "2024-02-06T18:00:00-08:00"
      precipitation_probability: 40
      is_daytime: false
      condition: rainy
      wind_bearing: 157.5
      temperature: 41
      dew_point: 41
      wind_speed: 5
      humidity: 87
    - detailed_description: >-
        A chance of rain. Mostly cloudy, with a high near 46. West southwest
        wind around 5 mph. Chance of precipitation is 40%.
      datetime: "2024-02-07T06:00:00-08:00"
      precipitation_probability: 40
      is_daytime: true
      condition: rainy
      wind_bearing: 247.5
      temperature: 46
      dew_point: 40
      wind_speed: 5
      humidity: 86
    - detailed_description: >-
        A chance of rain. Mostly cloudy, with a low around 40. Chance of
        precipitation is 30%.
      datetime: "2024-02-07T18:00:00-08:00"
      precipitation_probability: 30
      is_daytime: false
      condition: rainy
      wind_bearing: 90
      temperature: 40
      dew_point: 39
      wind_speed: 4
      humidity: 87
    - detailed_description: >-
        A chance of rain. Partly sunny, with a high near 46. Chance of
        precipitation is 30%.
      datetime: "2024-02-08T06:00:00-08:00"
      precipitation_probability: 30
      is_daytime: true
      condition: rainy
      wind_bearing: 180
      temperature: 46
      dew_point: 38
      wind_speed: 7
      humidity: 84
    - detailed_description: A chance of rain. Mostly cloudy, with a low around 38.
      datetime: "2024-02-08T18:00:00-08:00"
      precipitation_probability: 0
      is_daytime: false
      condition: rainy
      wind_bearing: 180
      temperature: 38
      dew_point: 38
      wind_speed: 7
      humidity: 85
    - detailed_description: A slight chance of rain. Partly sunny, with a high near 46.
      datetime: "2024-02-09T06:00:00-08:00"
      precipitation_probability: 0
      is_daytime: true
      condition: rainy
      wind_bearing: 157.5
      temperature: 46
      dew_point: 37
      wind_speed: 7
      humidity: 85
    - detailed_description: A chance of rain. Mostly cloudy, with a low around 38.
      datetime: "2024-02-09T18:00:00-08:00"
      precipitation_probability: 0
      is_daytime: false
      condition: rainy
      wind_bearing: 112.5
      temperature: 38
      dew_point: 37
      wind_speed: 6
      humidity: 83
    - detailed_description: A chance of rain. Partly sunny, with a high near 48.
      datetime: "2024-02-10T06:00:00-08:00"
      precipitation_probability: 0
      is_daytime: true
      condition: rainy
      wind_bearing: 157.5
      temperature: 48
      dew_point: 39
      wind_speed: 7.5
      humidity: 84
    - detailed_description: A chance of rain. Mostly cloudy, with a low around 40.
      datetime: "2024-02-10T18:00:00-08:00"
      precipitation_probability: 0
      is_daytime: false
      condition: rainy
      wind_bearing: 157.5
      temperature: 40
      dew_point: 39
      wind_speed: 9
      humidity: 83
    - detailed_description: A chance of rain. Partly sunny, with a high near 48.
      datetime: "2024-02-11T06:00:00-08:00"
      precipitation_probability: 0
      is_daytime: true
      condition: rainy
      wind_bearing: 292.5
      temperature: 48
      dew_point: 39
      wind_speed: 7
      humidity: 84
    - detailed_description: A chance of rain. Mostly cloudy, with a low around 38.
      datetime: "2024-02-11T18:00:00-08:00"
      precipitation_probability: 0
      is_daytime: false
      condition: rainy
      wind_bearing: 45
      temperature: 38
      dew_point: 39
      wind_speed: 7
      humidity: 83

**Comment by DarthSonic** [comment]
For me it works in preview but not when published to dashboard:

![image](https://github.com/mlamberts78/weather-chart-card/assets/3968605/7637d36e-ac0e-4b7e-bfdc-87a9c67d5275)

You can see other weather cards works fine.

**Comment by brezuicabogdan** [comment]
Same issue here - weather forecast ifo is present but not shown on the card. Hourly forecast is shown correctly

**Comment by fancygaphtrn** [comment]
To mlamberts78.   This is a link to what I use,  that includes NWS and the screen resizing issue.   It's somewhat a fork/hack of many of the weather-chart-card forks, including some from yours.  Thanks.
https://github.com/fancygaphtrn/lovelace-weather-card-chart/tree/master

**Comment by mlamberts78** [comment]
The card only supports daily and hourly forecasts provided by the weather integrations.
Since NWS is not providing a daily forecast it is not possible to use this card to show a daily forecast with the NWS integration.
Please use another weather integration which is supporting daily forecast to use this card to show a daily forecast.

**Comment by MichaelStruck** [comment]
@mlamberts78 It feels like an opportunity to use these twice daily forecasts to put a high/low display on the chart similarly to how the daily update looks. Is it categorically 'no' that you will not be developing these features, or will you be looking at this in the future?
