### ISSUE TITLE
Not able to show more than 5 days in the forecast

### ISSUE THREAD

**Issue by creed205** [mlamberts78/weather-chart-card#70]
I see that there is an image on the readme page where it shows 15 of forceast, but I am not able to find a setting to increase the number. 

![image](https://github.com/mlamberts78/weather-chart-card/assets/16401646/331dc504-05fc-4427-9273-ee4b5f4d2832)

 - WEATHER-CHART-CARD VERSION - 2.2.5
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE - 2024.1.6
 - OS: 11.4
 - Browser  - Chrome
 - Version - 121.0.6167.140

**Comment by mlamberts78** [comment]
The Weather card is only displaying what your weather integration is offering for data. You should use a weather integration that is providing more days of data.
The picture in the readme is using: https://github.com/briis/visualcrossing
