### ISSUE TITLE
alternate entity "feels_like" dont work

### ISSUE THREAD

**Issue by digi303** [mlamberts78/weather-chart-card#71]
the specification of an alternative sensor for the feels-like temperature is not used. 

At least the displayed value does not match the sensor value.
![Unbenannt](https://github.com/mlamberts78/weather-chart-card/assets/94383598/0ea80496-c001-4f33-ac58-af1341312486)

**Comment by TTLucian** [comment]
I believe there's still an issue here. Some sensors are shown, some are not. No ideea why.

<img width="1012" height="562" alt="Image" src="https://github.com/user-attachments/assets/08aa8017-8ee2-4110-9059-b585f76c297e" />

<img width="1004" height="620" alt="Image" src="https://github.com/user-attachments/assets/20bc9f8b-e629-46b6-9c7e-58d934dd0dfa" />

<img width="563" height="392" alt="Image" src="https://github.com/user-attachments/assets/c1268427-8e1c-4ca7-806d-c1a0c2e11a49" />

<img width="566" height="395" alt="Image" src="https://github.com/user-attachments/assets/2d7b1b30-4dd8-4ac1-9fa9-bbcae6d83cb8" />
