### ISSUE TITLE
Clock with seconds

### ISSUE THREAD

**Issue by Rudd-O** [mlamberts78/weather-chart-card#72]
Can the clock with seconds be shown to the side of the *Show Main* information?  Thanks.

**Comment by mlamberts78** [comment]
I tried implementing this but it doesn't work properly. Sometimes seconds are skipped. It probably has something to do with how HA refreshes the screen/cards. Will not implement this now.

**Comment by Rudd-O** [comment]
Can you please check how the clock-weather-card folks implement it?  It works fine for them, but they had to add a thing.  You cannot rely on HA refresh routine to refresh the clock in that case.

* https://github.com/pkissling/clock-weather-card/commit/1495be0baff0131fa348fb71a20b6b77ec1102d3
* https://github.com/pkissling/clock-weather-card/commit/56e293dd79fc550ff07951adccf4cfbcf31024c3

**Comment by mlamberts78** [comment]
Thanks for the tip, will reopen and have a look.
