### ISSUE TITLE
Hide Temperature Section

### ISSUE THREAD

**Issue by Maddin1684** [mlamberts78/weather-chart-card#75]
Hey,

Is it possible to hide the temperature section (current weather), so that only the conditions are shown?

Is it also possible to reduce the space between the current weather and the forecast?

**Comment by mlamberts78** [comment]
You can hide the temperature section by using `show_main: false`
It is not possible to reduce the space between the current weather and the forecast.

**Comment by Maddin1684** [comment]
Thank you, but then I don’t see the current conditions (Icon and weather). 

I only want to hide the temp, but my temp is shown separately on a chart card.

**Comment by mlamberts78** [comment]
Ok, I will make it optional to hide the current temperature in a next release.

**Comment by Maddin1684** [comment]
Thanks. 
Would be great, if it could like this (a combination of weather card and weather-chart-card)
![Uploading IMG_9575.jpeg…]()
