### ISSUE TITLE
Sunrise/set not being shown in 24h format and missing wind direction

### ISSUE THREAD

**Issue by janchrillesen** [mlamberts78/weather-chart-card#76]
**Describe the bug**
Sunrise and sunset is shown as AM/PM (12 hour format) despite use_12hour_format being set to "false"
Wind direction/bearing is being show as degrees and not text. Also arrow is missing

**To Reproduce**

Enable the following options:

use_12hour_format: false
winddir: <entify from weatherstation>

**Expected behavior**
Would expect sunrise/sunset being shown in 24H format, instead of AM/PM, when use_12hour_format  is set to false

Would expect winddirection being shown as text (for instance NW, instead of 315) - also an arrow being shown, indicating the direction. I am not sure why this not work as all screenshots in the examples looks correct

**Screenshots**

<img width="967" alt="Skærmbillede 2024-02-07 kl  22 41 32" src="https://github.com/mlamberts78/weather-chart-card/assets/6328883/06737a8a-9ec3-4230-bae4-a1705039544a">

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION: 2.2.6 (latest in HACS)
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE (e.g.  2024.2.0 - was also broken in latest 2024.1.x)
 - OS: [e.g. 10.3, venv, etc.]. HomeAssistant OS 11.5
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 121.0.6167.139

**Additional context**
Weather station data is coming from the Ecowitt integration in HA, using a GW2000 gateway and WS90 weather station
Weather forecast data is using met.no integration in HA

**Comment by mlamberts78** [comment]
The use_12hour_format is part of the forecast setting, not for the attributes. The sunset and sunrise are now showing the time based on the language settings. If you have you general HA language on English I would like to propose to use English (GB) if you would like to have 24h format.

The windir alternate sensor in degrees I can reproduce and will provide a fix in a next release.

**Comment by janchrillesen** [comment]
Thanks. I can confirm that updating the language settings does fix the 24h timeformat issue

**Comment by erkr** [comment]
I think the time and date format better follow the time and date formats as configured in the user profile. 
In my case, I use time (24h) and date (ddmmyyyy) formats as used in most European countries (except the UK) while my language is English.
![image](https://github.com/mlamberts78/weather-chart-card/assets/4363599/f9622f3b-369b-4dd5-95ff-4cee0f14c845)

**Comment by mlamberts78** [comment]
@erkr I will look for the option to change the forecast setting to a global setting, then it is fully controlled within the card.

**Comment by erkr** [comment]
Global flag for 12h works great, thanks
