### ISSUE TITLE
Change number of hours forecast to be shown

### ISSUE THREAD

**Issue by ministryofsillywalks** [mlamberts78/weather-chart-card#78]
**Is your feature request related to a problem? Please describe.**
First of all thanks for the great card!
Currently, the hourly forecast always shows the next 7 hours. It would be great if this number could be set higher, so for example show the next 12 hours. This is especially useful when looking at the card in the morning and trying to figure out what the rest of the day will be like. 

**Describe the solution you'd like**
Give an option to select the number of hours (maybe also days) to preview and not have it set fixed to 7 hours/days.

**Additional context**

**Comment by catartica76** [comment]
very nice card
I too felt the same need

**Comment by mlamberts78** [comment]
The amount of displayed forecasts are based on the size of the card and the size of the screen, when a user is able to change it, it will mess up the card and the forecasts will be overlapping. So there is no hard setting on 7, but it is automatically adjusting.
You can create a dashboard with one panel, that will give more room and will show more hours.
