### ISSUE TITLE
The card keeps vanishing and have to reinstall

### ISSUE THREAD

**Issue by tigers75** [mlamberts78/weather-chart-card#79]
**Describe the bug**
After installation the card works good, but some time later, on both other devices and even the same device where it was installed and worked, it just disappears.
Reinstalling it form HACS fixes it, but only for some time.

**To Reproduce**
1. Install card, configure;
2. Wait some time
3. change dashboard and get back to the one with the card
4. it shows an error
5. try to refresh the browser
6. still error
7. try to force a full cache refresh (CTRL+F5)
8. still error

**Expected behavior**
The card shouldn't need to be reinstalled at every use.

**Screenshots**
![image](https://github.com/mlamberts78/weather-chart-card/assets/37505492/15abe689-c90b-453a-a949-2778933c2a08)

**Desktop (please complete the following information):**
 - Using latest version available
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE: 2024.2.0, was the same in 2024.1
 - OS: Any, even the official app
 - Browser Any
 - Version Any

**Additional context**

**Comment by birostris** [comment]
I have a similar but not identical issue, but I guess it is the same technical issue.
I can see in HACS that I have intalled the card, but I have only seen it once in the UI-editor.
I keep getting `Custom element doesn't exist: weather-chart-card. ` when I create a manual card

**Comment by tigers75** [comment]
Installed 2.2.7 but still the same problem: the card is OK only when I install it, even opening a new window in the same browser is enough to break it (even reloading the page where it works, whether with F5 or CTRL+F5 it breaks):
![image](https://github.com/mlamberts78/weather-chart-card/assets/37505492/9115fabd-4384-4387-9edd-6a5e299cdd05)

**Comment by mlamberts78** [comment]
> Installed 2.2.7 but still the same problem: the card is OK only when I install it, even opening a new window in the same browser is enough to break it (even reloading the page where it works, whether with F5 or CTRL+F5 it breaks): ![image](https://private-user-images.githubusercontent.com/37505492/303634495-9115fabd-4384-4387-9edd-6a5e299cdd05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0Nzc5NDgsIm5iZiI6MTcwNzQ3NzY0OCwicGF0aCI6Ii8zNzUwNTQ5Mi8zMDM2MzQ0OTUtOTExNWZhYmQtNDM4NC00Mzg3LTllZGQtNmE1ZTI5OWNkZDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDExMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZTYyMzMwYTkxNzhkNDRkYTVmNGUyMTY2YzM3MmNlMWE0NDY2OTczNDU3OGJlNWY4MjJjYTMwZjk2YzgyODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5FVB7tR32VJyonyK1bH8zi6sfj6A3UZh9_50xRTHhr0)

That's strange, then it is not the same problem as #51 , I was able to reproduce on my Samsung family hub and found that the latest lit version was not compatible with older devices.  

Can you try the following?

- Uninstall card from HACS
- Remove the card from resources (Settings -> Dashboards -> 3 dots -> resources -> **delete** weather-chart-card entry)
- restart HA
- Install the card from HACS again

**Comment by tigers75** [comment]
Still nothing.
Only thing I noticed is there wasn't any entry to remove form the dashboard resources menu after uninstalling (while there's one now that I have installed again).

**Comment by fugazzy** [comment]
For me the new version works fine so far!

**Comment by nicolacavallo84** [comment]
I have the same problem too. Even reinstalling from hacs the problem persists

**Comment by harriseeall** [comment]
I have also the same problem. Only deleting restart and reinstall works for a short moment. Same on Windows and IOS. With 2.2.6 and 2.2.7 still the same.

**Comment by nicolacavallo84** [comment]
Only by returning to version 2.2.5 does it work again.

**Comment by tigers75** [comment]
Tried rolling back up to 2.2.5 but none works. I had just installed the card, so I can't tell for sure if it was working fine with HA 2024.1.

**Comment by mlamberts78** [comment]
@tigers75 Can you test version 2.2.9? It seems the card was sometimes conflicting with anoter card, that sould be solved now.

**Comment by tigers75** [comment]
Seems to work good so far, if it keeps up I think we can close this issue.

**Comment by birostris** [comment]
2.2.9 works for me as well

**Comment by janrockstedt** [comment]
I have the same problem with 2.2.9.
Remove the and download it again from HACS works for a while.
