### ISSUE TITLE
feels like temperature

### ISSUE THREAD

**Issue by digi303** [mlamberts78/weather-chart-card#81]
In the latest version (2.2.7), the value of the perceived temperature is no longer rounded :-)
pretty accurate, but is that the way it should be? :-)
![Unbenannt](https://github.com/mlamberts78/weather-chart-card/assets/94383598/7d08facd-7ab2-4bb7-812d-0184065881d5)

**Comment by mlamberts78** [comment]
It was never rounded, no changes for this in the latest version. It is pure displaying the sensor value. But I can have a look to round it to avoid this kind of behavior.

**Comment by digi303** [comment]
That's interesting, then the behaviour must come from HA version 2024.2.0/1.
Unfortunately, the rounding setting in the entity settings of the sensor has no influence on this.

**Comment by dselzle** [comment]
This does not seem to be fixed for me in 2.3.0:
![Screenshot_20240218-204409.png](https://github.com/mlamberts78/weather-chart-card/assets/40190089/0835db4c-f61a-477a-8679-9207a5c32b50)
