### ISSUE TITLE
Does not display the weather forecast in the card

### ISSUE THREAD

**Issue by Pro100x3mal** [mlamberts78/weather-chart-card#82]
**Describe the bug**
In the custom weather provider Gismeteo (https://github.com/Limych/ha-gismeteo) does not display the weather forecast in the card
![IMG_4479](https://github.com/mlamberts78/weather-chart-card/assets/87969152/4d1f171a-9b62-4124-b6b6-d2a2d1a57093)
![IMG_4480](https://github.com/mlamberts78/weather-chart-card/assets/87969152/300363af-f6be-4ece-9905-5970775e284f)

**Comment by welle** [comment]
Same issue with OpenWeatherMap :(

**Comment by mlamberts78** [comment]
I see with the gismeteo you should select the mode:
mode:
(string) (Optional)
Can specify hourly or daily. Select hourly for a three-hour forecast for 24h, daily for daily forecast for a week.
Default value: hourly

Did you do that and selected the same mode as used in the card?

**Comment by mlamberts78** [comment]
@Pro100x3mal Can you provide output of the weather data?

Developer tools - services - Get weather forecast.

And do you see the same behavior on other weather cards?

**Comment by mlamberts78** [comment]
This is not a card issue, but an issue with the weather integration Gismeteo.
