### ISSUE TITLE
The name of the day is incorrectly changed to the time 12:00.

### ISSUE THREAD

**Issue by RH-Dreambox** [mlamberts78/weather-chart-card#83]
Every day the graph header changes from the name of the day to the time 12:00. This happens sometime between 12:00 and 15:00 (unfortunately I don't know the exact time).
In the morning of the next day, the name of the day is displayed correctly again.
Weather Chart is configured to show Forecast type: Daily forecast.

I use smhi_weather (sweden) and it shows forecast for 10 days.

If I change the weather provider to MetNO (norge) the header is shown correctly to the name of the day.
I have tried to change the Forecast type from Daily to Hourly and back, but this does not help.
I use Weather state V2.2.7

![Weather state hours](https://github.com/mlamberts78/weather-chart-card/assets/35836981/571a86ef-d366-43c7-845d-948c471b887b)

**Comment by mlamberts78** [comment]
Hello, can you provide output of the weather data at the time this is the case?

Developer tools - services - Get weather forecast.

And do you see the same behavior on other weather cards at the same time?

**Comment by RH-Dreambox** [comment]
Hi mlamberts78,
Is the data below what you need?
At 13:59 local time, the names of the days were displayed correctly.
When I looked again at 14:03 local time, the name of the day had been changed to 12:00.
The code I attach is copied a few minutes later.

`forecast:
  - datetime: "2024-02-12T13:00:00"
    condition: snowy
    wind_bearing: 77
    cloud_coverage: 100
    temperature: -1
    templow: -1
    pressure: 1000
    wind_gust_speed: 7.3
    wind_speed: 2.9
    precipitation: 8.1
    humidity: 95
  - datetime: "2024-02-13T12:00:00"
    condition: cloudy
    wind_bearing: 196
    cloud_coverage: 100
    temperature: 1
    templow: -2
    pressure: 1010
    wind_gust_speed: 3.9
    wind_speed: 1.6
    precipitation: 1.3
    humidity: 92
  - datetime: "2024-02-14T12:00:00"
    condition: cloudy
    wind_bearing: 138
    cloud_coverage: 100
    temperature: 2
    templow: 0
    pressure: 1016
    wind_gust_speed: 6.1
    wind_speed: 2.9
    precipitation: 0.4
    humidity: 99
  - datetime: "2024-02-15T12:00:00"
    condition: cloudy
    wind_bearing: 99
    cloud_coverage: 100
    temperature: 3
    templow: 1
    pressure: 1013
    wind_gust_speed: 2.6
    wind_speed: 0.6
    precipitation: 0
    humidity: 90
  - datetime: "2024-02-16T12:00:00"
    condition: pouring
    wind_bearing: 91
    cloud_coverage: 100
    temperature: 2
    templow: 0
    pressure: 1018
    wind_gust_speed: 7.7
    wind_speed: 3.6
    precipitation: 15
    humidity: 98
  - datetime: "2024-02-17T12:00:00"
    condition: sunny
    wind_bearing: 91
    cloud_coverage: 12
    temperature: -1
    templow: -5
    pressure: 1032
    wind_gust_speed: 9.4
    wind_speed: 2.9
    precipitation: 3.6
    humidity: 74
  - datetime: "2024-02-18T12:00:00"
    condition: cloudy
    wind_bearing: 189
    cloud_coverage: 100
    temperature: 1
    templow: -8
    pressure: 1033
    wind_gust_speed: 6.5
    wind_speed: 2.3
    precipitation: 0
    humidity: 67
  - datetime: "2024-02-19T12:00:00"
    condition: cloudy
    wind_bearing: 233
    cloud_coverage: 100
    temperature: 1
    templow: -3
    pressure: 1019
    wind_gust_speed: 8.4
    wind_speed: 3.5
    precipitation: 2.4
    humidity: 85
  - datetime: "2024-02-20T12:00:00"
    condition: cloudy
    wind_bearing: 281
    cloud_coverage: 100
    temperature: 1
    templow: -2
    pressure: 1018
    wind_gust_speed: 8
    wind_speed: 3.3
    precipitation: 1.2
    humidity: 78
  - datetime: "2024-02-21T12:00:00"
    condition: cloudy
    wind_bearing: 239
    cloud_coverage: 100
    temperature: 2
    templow: -3
    pressure: 1017
    wind_gust_speed: 8.4
    wind_speed: 3.7
    precipitation: 0
    humidity: 77
  - datetime: "2024-02-22T00:00:00"
    condition: cloudy
    wind_bearing: 205
    cloud_coverage: 100
    temperature: -3
    templow: -3
    pressure: 1016
    wind_gust_speed: 7.3
    wind_speed: 3.5
    precipitation: 0
    humidity: 93
`

**Comment by mlamberts78** [comment]
I’m able to reproduce and will be fixed in a next release.
