### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by FilipeOS** [mlamberts78/weather-chart-card#85]
**Describe the bug**
The time is always set to 12hours even when it's not selected.
The wind direction is always there.
Translation date and day not working 

**To Reproduce**
1. Add the options and test

**Expected behavior**
Time should be 24 hours by default since the option is 12hours.
Wind direction should hide when option is not selected.
Translate day of the week and months.
Better option would be to pick HA or user settings.

**Screenshots**
![Screenshot_20240211_225744_Home Assistant](https://github.com/mlamberts78/weather-chart-card/assets/18313286/3a7d5b9c-e972-4452-974e-03ee8a806dd2)
![Screenshot_20240211_225733_Home Assistant](https://github.com/mlamberts78/weather-chart-card/assets/18313286/08ba963e-ccb7-4d64-b8f5-a07ae07933b4)

**Desktop (please complete the following information):**
 - WEATHER-CHART-CARD VERSION 2.2.7
 - HOME ASSISTANT VERSION AND INSTALLATION TYPE hacs 1.34.0
Core 2024.2.1
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.1
 - OS: [e.g. 10.3, venv, etc.]
 - Browser HA android/chrome 
 - Version latest

**Additional context**

**Comment by a-abrar** [comment]
Hi **FilipeOS**, 
Thank you for the report! We'll update the code to default to 24-hour time, hide wind direction when not selected, fix translation, and consider user preferences for customization.

**Comment by FilipeOS** [comment]
Days in PT-PT

SEG
TER
QUA
QUI
SEX
SÁB
DOM 

months (11 Fev, not Fev 11)
JAN
FEV
MAR
ABR
MAR
JUN
JUL
AGO
SET
OUT
NOV
DEZ

**Comment by FilipeOS** [comment]
Hi, I should have told you the days, it's showing wrong.

Monday = Segunda - SEG
Tuesday = Terça - TER
Wednesday = Quarta - QUA
Thursday = Quinta - QUI
Friday = Sexta - SEX
Saturday = Sábado - SÁB
Sunday = Domingo - DOM 

![Screenshot_20240217_095517_Home Assistant](https://github.com/mlamberts78/weather-chart-card/assets/18313286/3220c598-c0a9-4513-b633-5f628e607151)

**Comment by FilipeOS** [comment]
Well, I think it's fine the days but it's selecting the wrong day?

**Comment by mlamberts78** [comment]
> Well, I think it's fine the days but it's selecting the wrong day?

What do you mean with " it's selecting the wrong day"

**Comment by FilipeOS** [comment]
I don't understand why you selecting always this blue day

**Comment by mlamberts78** [comment]
That is 20mm of rain that will fall that day…….
