### ISSUE TITLE
show_attributes default setting not according documentation

### ISSUE THREAD

**Issue by Earthweb-EWS** [mlamberts78/weather-chart-card#9]
In documentation is the show_attributes setting described as default=true, but in version 1.6.3 the setting is default=false.
Not a big problem, but maybe you can have a look at it :-)

**Comment by mlamberts78** [comment]
I cannot reproduce the issue, is show_attributes on false when you create a new card?

**Comment by Earthweb-EWS** [comment]
this is my config, without explicit define this setting, the values aren't showing in the card:

`    - type: custom:weather-chart-card
      entity: weather.buienradar
      temp: sensor.esp_weatherstation_sht3x_temperature
      humid: sensor.esp_weatherstation_sht3x_humidity
      show_main: true
      show_attributes: true
      forecast:
        labels_font_size: 16
      units:
        speed: Bft`

**Comment by mlamberts78** [comment]
Thanks for the clarification, I found the issue and the fix will be included in the next release.
