### ISSUE TITLE
Being able to adjust number of decimals

### ISSUE THREAD

**Issue by mbagge** [mlamberts78/weather-chart-card#90]
Most of the time decimals are not required on weather related values.
E.g. air pressure in hPa and with one decimal, not even our national weather service do that and it requires high precision sensors of a totally different kind that normally not are in use in home assistant environments.
The same goes with temperature, if one could choose to show decimals or not. It will give a cleaner look.

**Comment by mbagge** [comment]
Sorry about the air pressure example, nothing to complain over here :-), 
but I hope to have made my point anyway. :-)

**Comment by mlamberts78** [comment]
Card is just displaying sensor value, attributes are rounded and you can choose in the forecast settings to round the temperature for the forecast. For now I will leave it like this.
