### ISSUE TITLE
Are the wind directions in the forecast flipped 180 degrees?

### ISSUE THREAD

**Issue by codahq** [mlamberts78/weather-chart-card#95]
**Describe the bug**
I've noticed that the current value of wind direction always seems to be 180 degrees flipped from what is in my forecast.  Maybe this is anecdotal and I'm just happening to notice it at the wrong time or maybe my forecast data provider is just bad.  However, I'm reporting it because it seems like it's worth looking into.  In the repository screenshots they also seem flipped 180 degrees.  This has seemed to be true over the last 48 hours of frequent observation.

**To Reproduce**
1. Find a forecast provider that shows wind direction in the forecast and also has a current.
2. Create a weather-chart-card with the weather sensor.
3. Create an entity card with the current wind direction provided separately.

**Expected behavior**
The wind directions should match.

**Screenshots**
![image](https://github.com/mlamberts78/weather-chart-card/assets/6679555/7d02764c-4d9a-4ab7-9cce-37687a3cd7e3)
![image](https://github.com/mlamberts78/weather-chart-card/assets/6679555/f917e55d-0c4f-446d-a3d4-e1a61bd9422f)

**Desktop (please complete the following information):**
 - weather-chart-card 2.2.10
 - HA current stable channel release and supervised
 - Any client OS
 - Any browser
 - Any browser version

**Comment by mlamberts78** [comment]
For wind from south, arrow up is 100% correct.

**Comment by codahq** [comment]
> For wind from south, arrow up is 100% correct. https://windy.app/blog/what-is-wind-direction.html

Ah, thank you for that.  That is an important distinction.  It is wind from the south; not wind blowing south.  I did not realize that was how it is normally provided.  This means on my other card it needs to be configured like this or this. 

![image](https://github.com/mlamberts78/weather-chart-card/assets/6679555/126ca53f-2e04-4f5c-bfbb-98878762d667)
![image](https://github.com/mlamberts78/weather-chart-card/assets/6679555/125f37a1-174c-4232-ad1e-3d0b447a6314)

I'll have to add a label or something somewhere because the secondary cardinal direction is what's confusing.  W doesn't mean it's pointing west like a weather mane would point.  It means it's blowing out of the W.  

Thanks again!
