### ISSUE TITLE
Language and AM/PM

### ISSUE THREAD

**Issue by One1Tick** [mlamberts78/weather-chart-card#97]
HI, thanks for the card. Well appreciated.

1. It seems that "locale: fr" attribute only change the lang of the current weather condition but not the lang of the day on the top right part of the card, it stays always in "en".
2. Would be nice to also have "use_12hour_format: false" for the current time on the top right part of the card.

Thanks again.

**Comment by One1Tick** [comment]
Thanks for Feedback
1. OK, that's clear. PLease don't remove locale setting... Just add in the wiki the fact that this setting is only for the currnet weather condition language not the date.
2. Thanks
Best!

**Comment by TekFan** [comment]
Very nice card !
But the actual and sun time locked in 12H format is definitely annoying for non US users.
This should be set by the system locale automatically.
But otherwise, very appreciated.

**Comment by mlamberts78** [comment]
> Very nice card ! But the actual and sun time locked in 12H format is definitely annoying for non US users. This should be set by the system locale automatically. But otherwise, very appreciated.

Will be fixed in the next release, very soon.

**Comment by Ic3Nine** [comment]
> Very nice card ! But the actual and sun time locked in 12H format is definitely annoying for non US users. This should be set by the system locale automatically. But otherwise, very appreciated.

Also sucks for us US users that don't like AM/PM format. :)
